<?php
/**
 * Gibbon, Flexible & Open School System
 * Copyright (C) 2010, Ross Parker
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 * Date: 24/01/2019
 * Time: 09:41
 */
namespace Gibbon;

use Gibbon\Database\Connection;
use Gibbon\Database\Result;
use PhpOffice\PhpSpreadsheet\Spreadsheet as SpreadsheetBase;
use PhpOffice\PhpSpreadsheet\Writer\Xls;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

class Spreadsheet extends SpreadsheetBase
{
    /**
     * @var string
     */
    private $fileName = '';

    /**
     * isSpreadsheetSizeOK
     *
     * @param Connection $pdo
     * @param int $maxCells
     * @return bool
     */
    public function isSpreadsheetSizeOK(Connection $pdo, int $maxCells = 8000): bool
    {
        return $pdo->getResult() ? ($pdo->getResult()->columnCount (  ) * $pdo->getResult()->rowCount ( ) > $maxCells ? false : true) : true;
    }

    /**
     * Export Worksheet
     * @param bool $openXML
     * @param string $name
     * @throws \PHPExcel_Writer_Exception
     * @throws \PhpOffice\PhpSpreadsheet\Writer\Exception
     */
    public function exportWorksheet($openXML = true)
    {
        // Instantiate a Writer to create an OfficeOpenXML Excel .xlsx file
        // Write the Excel file to filename some_excel_file.xlsx in the current directory
        if ($openXML) {
            $objWriter = new Xlsx($this);
        } else {
            $this->fileName = substr($this->getFileName(), 0, -1);
            $objWriter = new Xls($this);
        }
        // Write the Excel file to filename some_excel_file.xlsx in the current directory
        $this->setHeader();

        $objWriter->save('php://output');
        die();
    }

    /**
     * Set Header
     * this function used to set the header variable
     */
    private function setHeader()
    {
        header('Content-type: application/vnd.ms-excel');
        header('Content-Disposition: attachment; filename="' . $this->getFileName() . '"');
        header("Expires: 0");
        header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
        header("Cache-Control: private", false);
    }

    /**
     * Define Worksheet
     * @param string $fileName
     */
    public function defineWorksheet(string $fileName = '')
    {
        $this->getProperties()->setCreator(__("Gibbon Edu using PHPSpreadsheet"));
        $this->getProperties()->setLastModifiedBy(__("Gibbon"));
        $this->getProperties()->setTitle(__("Office 2007 XLSX Test Document"));
        $this->getProperties()->setSubject(__("Office 2007 XLSX Test Document"));
        $this->getProperties()->setDescription(__('This information is confidential. Generated by Gibbon (https://gibbonedu.org).'));
        $this->fileName = $fileName ?: $this->getFileName();
        if (substr($this->fileName, strlen($this->fileName) - 4) === '.xls')
            $this->fileName .= 'x';
    }

    /**
     * getFileName
     * @return string
     */
    public function getFileName(): string
    {
        return $this->fileName = $this->fileName ?: 'No_Name_Set.xlsx';
    }

    /**
     * E xport with Query Result
     * @param Result $tmprst
     * @param string $excel_file_name
     * @throws \PHPExcel_Writer_Exception
     * @throws \PhpOffice\PhpSpreadsheet\Exception
     * @throws \PhpOffice\PhpSpreadsheet\Writer\Exception
     */
    function exportWithQueryResult(Result $tmprst, string $excel_file_name)
    {
        $body = NULL ;

        $this->defineWorkSheet($excel_file_name);
        $this->getProperties()->setTitle("Gibbon Query Dump");
        $this->getProperties()->setSubject("Gibbon Query Dump");
        $this->getProperties()->setDescription("Dump of Query Results generated by Gibbon");
        $this->getDefaultStyle()->getFont()->setName('Arial');
        $this->getDefaultStyle()->getFont()->setSize(11);

        $rNum = 0;
        while($row = $tmprst->fetch()) {
            $rNum++;
            if ($rNum === 1)
            {
                // Row 1 is the headers.
                $cNum = 0;
                foreach($row as $name=>$value )
                {
                    $cNum++ ;
                    $this->getActiveSheet()->setCellValueByColumnAndRow($cNum, $rNum, ucfirst($name));
                }
                $this->getActiveSheet()->getStyle('1:1')->applyFromArray([
                    'font' => [
                        'bold' => true,
                    ],
                ]);
                $rNum++;
            }
            $cNum = 0 ;
            foreach($row as $value)
            {
                $cNum++ ;
                $this->getActiveSheet()->setCellValueByColumnAndRow($cNum, $rNum, $value);
            }
        }

        foreach(range(1, $cNum) as $col )
            $this->getActiveSheet()->getColumnDimensionByColumn($col)->setAutoSize(true);

        $this->exportWorksheet();
    }
}