<?php

/*
Gibbon: the flexible, open school platform
Founded by Ross Parker at ICHK Secondary. Built by Ross Parker, Sandra Kuipers and the Gibbon community (https://gibbonedu.org/about/)
Copyright © 2010, Gibbon Foundation
Gibbon™, Gibbon Education Ltd. (Hong Kong)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

//USE ;end TO SEPERATE SQL STATEMENTS. DON'T USE ;end IN ANY OTHER PLACES!

$sql = array();
$count = 0;

// v24.0.00 and earlier removed to reduce file size
// Systems using older versions can update using prior release from https://github.com/GibbonEdu/core/releases

//v25.0.00
++$count;
$sql[$count][0] = '25.0.00';
$sql[$count][1] = "
ALTER TABLE `gibbonMessenger` ADD `confidential` ENUM('N','Y') NOT NULL DEFAULT 'N' AFTER `smsReport`;end
INSERT INTO `gibbonAction` (`gibbonModuleID`, `name`, `precedence`, `category`, `description`, `URLList`, `entryURL`, `entrySidebar`, `menuShow`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES((SELECT gibbonModuleID FROM gibbonModule WHERE name='Messenger'), 'New Message_confidential', 0, 'Manage Messages', 'Enable users to send confidential messages which are not listed in Manage Messages for any other user.', 'messenger_post.php', 'messenger_post.php', 'Y', 'N', 'Y', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N');end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES ('001', (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Messenger' AND gibbonAction.name='New Message_confidential'));end
ALTER TABLE `gibbonCourseClass` ADD `enrolmentMin` int(4) DEFAULT NULL AFTER `attendance`;end
ALTER TABLE `gibbonCourseClass` ADD `enrolmentMax` int(4) DEFAULT NULL AFTER `enrolmentMin`;end
INSERT INTO `gibbonAction` (`gibbonModuleID`, `name`, `precedence`, `category`, `description`, `URLList`, `entryURL`, `entrySidebar`, `menuShow`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES((SELECT gibbonModuleID FROM gibbonModule WHERE name='Timetable Admin'), 'Timetable Settings', 0, 'Settings', 'Manage settings to control timetable functionality.', 'ttSettings.php', 'ttSettings.php', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N');end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES ('001', (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Timetable Admin' AND gibbonAction.name='Timetable Settings'));end
INSERT INTO `gibbonSetting` (`scope`, `name`, `nameDisplay`, `description`, `value`) VALUES ('Timetable Admin', 'enrolmentMinDefault', 'Minimum Enrolment Default', 'The default value for minimum class enrolment.', '');end
INSERT INTO `gibbonSetting` (`scope`, `name`, `nameDisplay`, `description`, `value`) VALUES ('Timetable Admin', 'enrolmentMaxDefault', 'Maximum Enrolment Default', 'The default value for maximum class enrolment.', '');end
INSERT INTO `gibbonNotificationEvent` (`event`, `moduleName`, `actionName`, `type`, `scopes`, `active`) VALUES ('New Investigation', 'Individual Needs', 'Manage Investigations', 'Core', 'All,gibbonPersonIDStudent,gibbonYearGroupID', 'Y');end
ALTER TABLE `gibbonSchoolYearSpecialDay` CHANGE `type` `type` ENUM('School Closure','Timing Change','Off Timetable');end
ALTER TABLE `gibbonSchoolYearSpecialDay` ADD `gibbonYearGroupIDList` VARCHAR(255) NULL AFTER `schoolClose`, ADD `gibbonFormGroupIDList` VARCHAR(255) NULL AFTER `gibbonYearGroupIDList`;end
ALTER TABLE `gibbonSchoolYearSpecialDay` ADD `context` ENUM('Year Group','Form Group') NULL AFTER `schoolClose`;end
ALTER TABLE `gibbonSchoolYearSpecialDay` ADD `cancelActivities` ENUM('Y','N') DEFAULT 'N' NULL AFTER `gibbonFormGroupIDList`;end
ALTER TABLE `gibbonHook` CHANGE `type` `type` ENUM('Public Home Page','Student Profile','Parental Dashboard','Staff Dashboard','Student Dashboard','Report Writing','Staff Profile','Lesson Planner') CHARACTER SET utf8 NULL DEFAULT NULL;end
ALTER TABLE `gibbonPlannerEntry` ADD `fields` TEXT NULL AFTER `gibbonPersonIDLastEdit`;end
ALTER TABLE `gibbonMessenger` ADD `status` ENUM('Draft','Sending','Sent') NOT NULL DEFAULT 'Sent' AFTER `gibbonSchoolYearID`;end
ALTER TABLE `gibbonMessenger` ADD `emailFrom` VARCHAR(75) NULL AFTER `timestamp`;end
ALTER TABLE `gibbonMessenger` ADD `emailReplyTo` VARCHAR(75) NULL AFTER `emailFrom`;end
ALTER TABLE `gibbonMessengerReceipt` ADD `sent` ENUM('N','Y') NOT NULL DEFAULT 'N' AFTER `gibbonPersonID`;end
ALTER TABLE `gibbonMessengerReceipt` ADD `nameListStudent` TEXT NULL AFTER `gibbonPersonIDListStudent`;end
UPDATE `gibbonMessengerReceipt` SET sent='Y';end
UPDATE `gibbonAction` SET URLList='messenger_manage.php,messenger_manage_delete.php,messenger_manage_edit.php,messenger_manage_report.php,messenger_send.php' WHERE name LIKE 'Manage Messages_%' AND gibbonModuleID=(SELECT gibbonModuleID FROM gibbonModule WHERE name='Messenger');end
ALTER TABLE gibbonMarkbookColumn MODIFY name VARCHAR(40);end
ALTER TABLE `gibbonTTSpaceBooking` ADD `reason` VARCHAR(255) NOT NULL AFTER `timeEnd`;end
UPDATE `gibbonAction` SET `URLList` = 'tt.php, tt_add.php, tt_edit.php, tt_delete.php, tt_import.php, tt_edit_day_add.php, tt_edit_day_edit.php, tt_edit_day_delete.php, tt_edit_day_edit_class.php, tt_edit_day_edit_class_delete.php, tt_edit_day_edit_class_add.php, tt_edit_day_edit_class_edit.php, tt_edit_day_edit_class_exception.php, tt_edit_day_edit_class_exception_add.php, tt_edit_day_edit_class_exception_delete.php,tt_edit_byClass.php' WHERE name='Manage Timetables' AND gibbonModuleID=(SELECT gibbonModuleID FROM gibbonModule WHERE name='Timetable Admin');end
ALTER TABLE `gibbonAttendanceLogPerson` ADD `gibbonTTDayRowClassID` INT(12) UNSIGNED ZEROFILL NULL AFTER `gibbonCourseClassID`;end
ALTER TABLE `gibbonAttendanceLogCourseClass` ADD `gibbonTTDayRowClassID` INT(12) UNSIGNED ZEROFILL NULL AFTER `gibbonCourseClassID`;end
INSERT IGNORE INTO `gibboni18n` (`code`, `name`, `version`, `active`, `installed`, `systemDefault`, `dateFormat`, `dateFormatRegEx`, `dateFormatPHP`, `rtl`) VALUES ('lt_LT', 'Lietuvių Kalba - Lithuanian', '25.0.00', 'Y', 'N', 'N', 'yyyy.mm.dd', '/^[0-9]{4}.(0[1-9]|1[0-2]).(0[1-9]|[1-2][0-9]|3[0-1])$/', 'Y.m.d', 'N');end
ALTER TABLE `gibbonFormField` ADD `defaultValue` VARCHAR(255) NULL DEFAULT NULL AFTER `conditional`;end
ALTER TABLE `gibbonDepartment` ADD `fields` TEXT NULL AFTER `sequenceNumber`;end
ALTER TABLE `gibbonStudentEnrolment` ADD `fields` TEXT NULL AFTER `rollOrder`;end
CREATE TABLE `gibbonStaffDuty` ( `gibbonStaffDutyID` INT(6) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT , `gibbonDaysOfWeekIDList` VARCHAR(30) NULL, `name` VARCHAR(90) NOT NULL , `timeStart` TIME NOT NULL , `timeEnd` TIME NOT NULL , `sequenceNumber` INT(6) NOT NULL , PRIMARY KEY (`gibbonStaffDutyID`)) ENGINE = InnoDB CHARSET=utf8;end
CREATE TABLE `gibbonStaffDutyPerson` ( `gibbonStaffDutyPersonID` INT(10) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT , `gibbonStaffDutyID` INT(10) UNSIGNED ZEROFILL NOT NULL, `gibbonDaysOfWeekID` INT(2) UNSIGNED ZEROFILL NOT NULL , `gibbonPersonID` INT(10) UNSIGNED ZEROFILL NOT NULL, PRIMARY KEY (`gibbonStaffDutyPersonID`), UNIQUE KEY (`gibbonStaffDutyID`, `gibbonDaysOfWeekID`, `gibbonPersonID`) ) ENGINE = InnoDB CHARSET=utf8;end
INSERT INTO `gibbonAction` (`gibbonModuleID`, `name`, `precedence`, `category`, `description`, `URLList`, `entryURL`, `entrySidebar`, `menuShow`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES((SELECT gibbonModuleID FROM gibbonModule WHERE name='Staff'), 'Duty Schedule_edit', 0, 'Reports', 'Manage the staff duty schedule.', 'staff_duty.php,staff_duty_edit.php', 'staff_duty.php', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N');end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES ('001', (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Staff' AND gibbonAction.name='Duty Schedule_edit'));end
INSERT INTO `gibbonAction` (`gibbonModuleID`, `name`, `precedence`, `category`, `description`, `URLList`, `entryURL`, `entrySidebar`, `menuShow`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES((SELECT gibbonModuleID FROM gibbonModule WHERE name='Staff'), 'Duty Schedule_view', 0, 'Reports', 'View the staff duty schedule.', 'staff_duty.php', 'staff_duty.php', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N');end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES ('001', (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Staff' AND gibbonAction.name='Duty Schedule_view'));end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES ('002', (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Staff' AND gibbonAction.name='Duty Schedule_view'));end
ALTER TABLE `gibbonStaffCoverageDate` ADD `gibbonTTDayRowClassID` INT(12) UNSIGNED ZEROFILL NULL AFTER `gibbonStaffAbsenceDateID`;end
INSERT INTO `gibbonSetting` (`scope`, `name`, `nameDisplay`, `description`, `value`) VALUES ('Staff', 'coverageMode', 'Coverage Mode', 'Should teachers send coverage requests directly to substitutes, or will it be assigned for them?', 'Requested');end
INSERT INTO `gibbonSetting` (`scope`, `name`, `nameDisplay`, `description`, `value`) VALUES ('Staff', 'coverageInternal', 'Internal Coverage', 'If Yes, teachers can be assigned to cover each other. Otherwise, only users added through Manage Substitutes will be available for coverage.', 'N');end
ALTER TABLE `gibbonStaffCoverage` CHANGE `status` `status` ENUM('Requested','Accepted','Declined','Cancelled','Pending') NULL DEFAULT 'Requested';end
INSERT INTO `gibbonAction` (`gibbonModuleID`, `name`, `precedence`, `category`, `description`, `URLList`, `entryURL`, `entrySidebar`, `menuShow`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES((SELECT gibbonModuleID FROM gibbonModule WHERE name='Staff'), 'Daily Coverage Planner', 0, 'Coverage', '', 'coverage_planner.php,coverage_planner_assign.php,coverage_planner_unassign.php', 'coverage_planner.php', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N');end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES ('001', (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Staff' AND gibbonAction.name='Daily Coverage Planner'));end
ALTER TABLE `gibbonStaffCoverageDate` ADD `foreignTable` VARCHAR(60) NULL AFTER `gibbonStaffAbsenceDateID`;end
ALTER TABLE `gibbonStaffCoverageDate` CHANGE `gibbonTTDayRowClassID` `foreignTableID` INT(12) UNSIGNED ZEROFILL NULL DEFAULT NULL;end
ALTER TABLE `gibbonStaffCoverageDate` ADD INDEX(`foreignTable`, `foreignTableID`);end
ALTER TABLE `gibbonActivityStaff` ADD INDEX(`gibbonActivityID`, `gibbonPersonID`);end
UPDATE `gibbonNotificationEvent` SET moduleName='Admissions' WHERE moduleName='Students' AND event='New Application Form';end
UPDATE `gibbonNotificationEvent` SET moduleName='Admissions' WHERE moduleName='Students' AND event='New Application with SEN/Medical';end
UPDATE `gibbonNotificationEvent` SET moduleName='Admissions' WHERE moduleName='Students' AND event='Application Form Accepted';end
UPDATE `gibbonNotificationEvent` SET moduleName='Admissions' WHERE moduleName='Students' AND event='Student Withdrawn';end 
";

//v25.0.01
++$count;
$sql[$count][0] = '25.0.01';
$sql[$count][1] = "
ALTER TABLE `gibbonMessengerReceipt` CONVERT TO CHARACTER SET utf8;end
ALTER TABLE `gibbonFormUpload` CHANGE `name` `name` VARCHAR(255) CHARACTER SET utf8 NULL DEFAULT NULL;end
INSERT INTO `gibbonSetting` (`scope`, `name`, `nameDisplay`, `description`, `value`) VALUES ('System', 'allowableIframeSources', 'Allowable iFrame Sources', 'A comma separated list of domains that are allowed in embedded iFrames. All others will be removed from HTML content.', 'youtube.com,youtu.be,m.youtube.com,google.com,docs.google.com,drive.google.com,vimeo.com,player.vimeo.com');end

";

//v26.0.00
++$count;
$sql[$count][0] = '26.0.00';
$sql[$count][1] = "
ALTER TABLE `gibbonStaffCoverage` CHANGE `status` `status` ENUM('Requested','Accepted','Declined','Cancelled','Pending','Not Required') CHARACTER SET utf8 NULL DEFAULT 'Requested';end
ALTER TABLE `gibbonStaffDuty` ADD `nameShort` VARCHAR(20) NOT NULL AFTER `name`;end
UPDATE `gibbonLibraryItem` SET timestampUpdate = CURRENT_TIMESTAMP WHERE UNIX_TIMESTAMP(timestampUpdate) = 0;end
UPDATE `gibbonLibraryItem` SET timestampStatus = CURRENT_TIMESTAMP WHERE UNIX_TIMESTAMP(timestampStatus) = 0;end
UPDATE `gibbonLibraryItem` SET timestampCreator = CURRENT_TIMESTAMP WHERE UNIX_TIMESTAMP(timestampCreator) = 0;end
ALTER TABLE `gibbonLibraryItem` ADD `gibbonLibraryItemIDParent` INT(10) NULL DEFAULT NULL AFTER `gibbonLibraryItemID`;end
ALTER TABLE `gibbonMessengerReceipt` CHARACTER SET utf8;end
ALTER TABLE `gibbonMessengerReceipt` CONVERT TO CHARACTER SET utf8;end
INSERT INTO `gibbonNotificationEvent` (`event`, `moduleName`, `actionName`, `type`, `scopes`, `active`) VALUES ('Behaviour Record for IN Student', 'Behaviour', 'View Behaviour Records_all', 'Core', 'All,gibbonPersonIDStudent,gibbonYearGroupID', 'Y');end
INSERT INTO `gibbonSetting` (`scope`, `name`, `nameDisplay`, `description`, `value`) VALUES ('Students', 'emergencyFollowUpGroup', 'Follow-up Contacts', 'An optional list of staff to include in the follow-up contacts section.', '');end
UPDATE `gibbonAction` SET name='First Aid Record_editAll', precedence=2 WHERE name='First Aid Record' AND gibbonModuleID=(SELECT gibbonModuleID FROM gibbonModule WHERE name='Students');end
INSERT INTO `gibbonAction` (`gibbonModuleID`, `name`, `precedence`, `category`, `description`, `helpURL`, `URLList`, `entryURL`, `entrySidebar`, `menuShow`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES((SELECT gibbonModuleID FROM gibbonModule WHERE name='Students'), 'First Aid Record_viewOnlyAddNotes', 0, 'Medical', 'Allows user to view first aid records and add incident notes, but not add or edit records.', NULL, 'firstAidRecord.php,firstAidRecord_edit.php', 'firstAidRecord.php', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N');end
UPDATE `gibbonCountry` SET `iddCountryCode` = '856' WHERE `gibbonCountry`.`printable_name` ='Lao People\'s Democratic Republic';end
ALTER TABLE `gibbonMessenger` ADD `individualNaming` ENUM('N','Y') NOT NULL DEFAULT 'N' AFTER `emailReceiptText`;end
INSERT INTO `gibbonSetting` (`scope`, `name`, `nameDisplay`, `description`, `value`) VALUES ('Messenger', 'signatureTemplate', 'Signature Template', 'An HTML and Twig template used to add signatures to messages.', '----<br /><span style=\"font-weight: bold; color: #447caa;\">{{ preferredName }} {{ surname }}</span><br />{% if jobTitle is not empty %}<span style=\"font-style: italic;\">{{ jobTitle }}</span><br />{% endif %}{{ organisationName }}<br /></span>');end
ALTER TABLE `gibbonFormUpload` CHANGE `name` `name` VARCHAR(255) CHARACTER SET utf8 NULL DEFAULT NULL;end
INSERT IGNORE INTO `gibbonSetting` (`scope`, `name`, `nameDisplay`, `description`, `value`) VALUES ('System', 'allowableIframeSources', 'Allowable iFrame Sources', 'A comma separated list of domains that are allowed in embedded iFrames. All others will be removed from HTML content.', 'youtube.com,youtu.be,m.youtube.com,google.com,docs.google.com,drive.google.com,vimeo.com,player.vimeo.com');end
ALTER TABLE `gibbonFamily` CHANGE `status` `status` ENUM('Married','Separated','Divorced','De Facto','Other','Single') NOT NULL;end
UPDATE `gibbonAction` SET `categoryPermissionStudent` = 'Y', `categoryPermissionOther` = 'Y' WHERE name='Manage Facility Bookings_myBookings' AND gibbonModuleID=(SELECT gibbonModuleID FROM gibbonModule WHERE name='Timetable');end
UPDATE `gibbonAction` SET `categoryPermissionStudent` = 'Y', `categoryPermissionOther` = 'Y' WHERE name='View Timetable by Facility' AND gibbonModuleID=(SELECT gibbonModuleID FROM gibbonModule WHERE name='Timetable');end
ALTER TABLE `gibbonFirstAid` ADD `gibbonPersonIDFollowUp` INT(10) UNSIGNED ZEROFILL NULL AFTER `gibbonPersonIDFirstAider`;end
ALTER TABLE `gibbonMessenger` ADD `includeSignature` ENUM('N','Y') NOT NULL DEFAULT 'N' AFTER `individualNaming`;end
INSERT INTO `gibbonSetting` (`scope`, `name`, `nameDisplay`, `description`, `value`) VALUES ('System', 'notificationIntervalStaff', 'Staff Notification Interval', 'Frequency of notification icon update in status tray, for staff users. In thousands of a second.', '10000');end
INSERT INTO `gibbonSetting` (`scope`, `name`, `nameDisplay`, `description`, `value`) VALUES ('System', 'notificationIntervalOther', 'Other Notification Interval', 'Frequency of notification icon update in status tray, for all non-staff users. In thousands of a second.', '60000');end
INSERT INTO `gibbonNotificationEvent` (`event`, `moduleName`, `actionName`, `type`, `scopes`, `active`) VALUES ('Remove Stale Notifications', 'User Admin', 'Manage Users', 'CLI', 'All', 'Y');end
ALTER TABLE `gibbonLibraryItem` CHANGE `status` `status` ENUM('Available','In Use','Decommissioned','Lost','On Loan','Repair','Reserved','On Order') CHARACTER SET utf8 NOT NULL DEFAULT 'Available' COMMENT 'The current status of the item.';end
CREATE INDEX `gibbonPersonID` ON gibbonNotification(gibbonPersonID);end
";

//v27.0.00
++$count;
$sql[$count][0] = '27.0.00';
$sql[$count][1] = "
INSERT INTO `gibbonNotificationEvent` (`event`, `moduleName`, `actionName`, `type`, `scopes`, `active`) VALUES ('Activity Enrolment Added', 'Activities', 'View Activities', 'Core', 'All', 'Y');end
INSERT INTO `gibbonNotificationEvent` (`event`, `moduleName`, `actionName`, `type`, `scopes`, `active`) VALUES ('Activity Enrolment Removed', 'Activities', 'View Activities', 'Core', 'All', 'Y');end
INSERT INTO `gibbonNotificationEvent` (`event`, `moduleName`, `actionName`, `type`, `scopes`, `active`) VALUES ('Activity Status Changed', 'Activities', 'View Activities', 'Core', 'All', 'Y');end
ALTER TABLE `gibbonActivityStudent` CHANGE `status` `status` ENUM('Accepted','Pending','Waiting List','Not Accepted','Left') NOT NULL DEFAULT 'Pending';end
INSERT INTO `gibbonSetting` (`scope`, `name`, `nameDisplay`, `description`, `value`) VALUES ('User Admin', 'privacyOptionVisibility', 'Display privacy options?', 'If enabled, privacy options can be selected by users through the Data Updater and Application Form. If not enabled, privacy options can only be changed by staff through Manage Users.', 'Y');end
UPDATE `gibbonSetting` SET description='Comma-separated list of choices to make available if privacy options are turned on.' WHERE scope='User Admin' AND name='privacyOptions';end
ALTER TABLE `gibbonSpace` ADD `active` ENUM('N','Y') NOT NULL DEFAULT 'Y' AFTER `type`;end
UPDATE `gibbonAction` SET category='Learn' WHERE gibbonModuleID=(SELECT gibbonModuleID FROM gibbonModule WHERE name='School Admin') AND name='Individual Needs Settings';end
ALTER TABLE `gibbonPerson` CHANGE `departureReason` `departureReason` VARCHAR(100) NOT NULL;end
INSERT INTO `gibbonNotificationEvent` (`event`, `moduleName`, `actionName`, `type`, `scopes`, `active`) VALUES ('First Aid Qualification Expiry', 'Staff', 'Manage Staff', 'Core', 'All', 'Y');end
CREATE TABLE `gibbonLibraryShelf` ( `gibbonLibraryShelfID` INT(6) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT , `name` VARCHAR(90) NOT NULL, `active` ENUM('Y','N') NOT NULL DEFAULT 'N', `field` VARCHAR(90) NOT NULL, `fieldValue` VARCHAR(90), `type` ENUM('Manual','Automatic') NOT NULL DEFAULT 'Manual', `sequenceNumber` INT(6) NOT NULL, PRIMARY KEY (`gibbonLibraryShelfID`)) ENGINE = InnoDB CHARSET=utf8;end
INSERT INTO `gibbonAction` (`gibbonModuleID`, `name`, `precedence`, `category`, `description`, `helpURL`, `URLList`, `entryURL`, `entrySidebar`, `menuShow`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES((SELECT gibbonModuleID FROM gibbonModule WHERE name='Library'), 'Manage Library Shelves', 0, 'Catalog', 'Allows user to manage shelves displaying library items for library browsing.', NULL, 'library_manage_shelves.php, library_manage_shelves_add.php, library_manage_shelves_edit.php, library_manage_shelves_delete.php', 'library_manage_shelves.php', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N');end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES ('001', (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Library' AND gibbonAction.name='Manage Library Shelves'));end
CREATE TABLE `gibbonLibraryShelfItem` ( `gibbonLibraryShelfItemID` INT(6) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT , `gibbonLibraryItemID` INT(10) UNSIGNED ZEROFILL NOT NULL, `gibbonLibraryShelfID` INT(6) UNSIGNED ZEROFILL NOT NULL, PRIMARY KEY (`gibbonLibraryShelfItemID`)) ENGINE = InnoDB CHARSET=utf8;end
ALTER TABLE `gibbonLibraryShelf` ADD `shuffle` ENUM('N','Y') NOT NULL DEFAULT 'N' AFTER `active`;end
CREATE INDEX `gibbonMessengerID` ON gibbonMessengerTarget(`gibbonMessengerID`,`gibbonMessengerTargetID`);end
ALTER TABLE `gibbonBehaviour` ADD `gibbonMultiIncidentID` varchar(64) DEFAULT NULL;end
UPDATE `gibbonCountry` SET `printable_name` = 'Ivory Coast (Côte d\'Ivoire)', `iddCountryCode` = '225' WHERE `gibbonCountry`.`printable_name` = 'Cote D\'Ivoire';end
CREATE TABLE `gibbonBehaviourFollowUp` ( `gibbonBehaviourFollowUpID` INT(11) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT, `gibbonBehaviourID` INT(12) UNSIGNED ZEROFILL NOT NULL, `gibbonPersonID` INT(10) UNSIGNED ZEROFILL NOT NULL, `followUp` TEXT, `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`gibbonBehaviourFollowUpID`), KEY `gibbonBehaviourID` (`gibbonBehaviourID`));end
ALTER TABLE `gibbonReportingCriteriaType` ADD `options` TEXT NULL AFTER `gibbonScaleID`;end
INSERT INTO `gibbonNotificationEvent` (`event`, `moduleName`, `actionName`, `type`, `scopes`, `active`) VALUES ('Student Form Group Changed', 'Admissions', 'View Student Profile_full', 'Core', 'All,gibbonYearGroupID', 'Y');end
INSERT INTO `gibbonAction` (`gibbonModuleID`, `name`, `precedence`, `category`, `description`, `URLList`, `entryURL`, `entrySidebar`, `menuShow`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES((SELECT gibbonModuleID FROM gibbonModule WHERE name='Behaviour'), 'View Behaviour Records_my', 0, 'Behaviour Records', 'Enables users to view the behaviour records created by them', 'behaviour_view.php,behaviour_view_details.php', 'behaviour_view.php', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N');end
ALTER TABLE `gibbonMessenger` CHANGE `messageWall_date1` `messageWall_dateStart` date DEFAULT NULL;end
ALTER TABLE `gibbonMessenger` CHANGE `messageWall_date3` `messageWall_dateEnd` date DEFAULT NULL;end
ALTER TABLE `gibbonMessenger` DROP `messageWall_date2`;end
ALTER TABLE `gibbonMessenger` ADD `enableSharingLink` ENUM('N','Y') NOT NULL DEFAULT 'N';end
";

//v27.0.01
++$count;
$sql[$count][0] = '27.0.01';
$sql[$count][1] = "";

//v28.0.00
++$count;
$sql[$count][0] = '28.0.00';
$sql[$count][1] = "
INSERT IGNORE INTO `gibbonLanguage` (`gibbonLanguageID`, `name`) VALUES (NULL, 'Putonghua');end
ALTER TABLE `gibbonAttendanceLogPerson` ADD INDEX(`context`, `gibbonCourseClassID`);end
INSERT IGNORE INTO `gibbonAction` (`gibbonModuleID`, `name`, `precedence`, `category`, `description`, `URLList`, `entryURL`, `entrySidebar`, `menuShow`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES((SELECT gibbonModuleID FROM gibbonModule WHERE name='Reports'), 'Progress by Department', 0, 'Progress', 'View report writing progress by department and class.', 'progress_byDepartment.php', 'progress_byDepartment.php', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N');end
INSERT IGNORE INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES ('001', (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Reports' AND gibbonAction.name='Progress by Department'));end
ALTER TABLE `gibbonPersonStatusLog` ADD `gibbonPersonIDModified` INT(10) UNSIGNED ZEROFILL NULL AFTER `timestamp`;end
UPDATE `gibbonNotificationEvent` SET event='Student Notes' WHERE event='New Student Note';end
ALTER TABLE `gibbonStaffAbsence` CHANGE `status` `status` ENUM('Pending Approval','Approved','Declined','Cancelled') CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT 'Approved';end
UPDATE gibbonCountry SET iddCountryCode='82' WHERE printable_name='Korea, Republic of';end
UPDATE gibbonCountry SET iddCountryCode='850' WHERE printable_name='Korea, Democratic People\'s Republic of';end
UPDATE `gibboni18n` SET `active` = 'Y' WHERE `code` = 'el_GR';end
UPDATE gibbonModule SET author='Gibbon Foundation', url='https://gibbonedu.org' WHERE type='Core';end
CREATE TABLE `gibbonMessengerMailingList` ( `gibbonMessengerMailingListID` int(8) unsigned ZEROFILL NOT NULL AUTO_INCREMENT, `surname` varchar(60) DEFAULT NULL, `preferredName` varchar(60) DEFAULT NULL, `email` varchar(75) NOT NULL, `timestampCreated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`gibbonMessengerMailingListID`), UNIQUE KEY `email` (`email`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;end
INSERT IGNORE INTO `gibbonAction` (`gibbonModuleID`, `name`, `precedence`, `category`, `description`, `URLList`, `entryURL`, `entrySidebar`, `menuShow`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES((SELECT gibbonModuleID FROM gibbonModule WHERE name='Messenger'), 'Manage Mailing List', 0, 'Targets', 'Manage users within the schools\' external mailing list.', 'mailingList_manage.php, mailingList_manage_add.php, mailingList_manage_edit.php, mailingList_manage_delete.php', 'mailingList_manage.php', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N');end
INSERT IGNORE INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES ('001', (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Messenger' AND gibbonAction.name='Manage Mailing List'));end
ALTER TABLE `gibbonMessengerMailingList` ADD `key` varchar(40) DEFAULT NULL AFTER `email`;end
RENAME TABLE gibbonMessengerMailingList to gibbonMessengerMailingListRecipient;end
ALTER TABLE gibbonMessengerMailingListRecipient CHANGE gibbonMessengerMailingListID gibbonMessengerMailingListRecipientID int(8) unsigned ZEROFILL NOT NULL AUTO_INCREMENT;end
UPDATE gibbonAction SET name='Manage Mailing List Recipients', description='Manage users within the schools\' external mailing list.', `URLList`='mailingListRecipients_manage.php, mailingListRecipients_manage_add.php, mailingListRecipients_manage.php_edit, mailingListRecipients_manage_delete.php', `entryURL`='mailingListRecipients_manage.php' WHERE name='Manage Mailing List' AND gibbonModuleID=(SELECT gibbonModuleID FROM gibbonModule WHERE name='Messenger');end
CREATE TABLE `gibbonMessengerMailingList` ( `gibbonMessengerMailingListID` int(8) unsigned ZEROFILL NOT NULL AUTO_INCREMENT, `name` varchar(60) NOT NULL, `active` ENUM('Y','N') NOT NULL DEFAULT 'Y', `timestampCreated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`gibbonMessengerMailingListID`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;end
INSERT IGNORE INTO `gibbonAction` (`gibbonModuleID`, `name`, `precedence`, `category`, `description`, `URLList`, `entryURL`, `entrySidebar`, `menuShow`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES((SELECT gibbonModuleID FROM gibbonModule WHERE name='Messenger'), 'Manage Mailing Lists', 0, 'Targets', 'Manage the schools\' external mailing lists.', 'mailingLists_manage.php, mailingLists_manage_add.php, mailingLists_manage_edit.php, mailingLists_manage_delete.php', 'mailingLists_manage.php', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N');end
INSERT IGNORE INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES ('001', (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Messenger' AND gibbonAction.name='Manage Mailing Lists'));end
ALTER TABLE gibbonMessengerMailingListRecipient ADD `organisation` varchar(60) DEFAULT NULL AFTER `email`;end
ALTER TABLE gibbonMessengerMailingListRecipient ADD `gibbonMessengerMailingListIDList` TEXT DEFAULT NULL AFTER `organisation`;end
INSERT INTO `gibbonAction` (`gibbonModuleID`, `name`, `precedence`, `category`, `description`, `URLList`, `entryURL`, `entrySidebar`, `menuShow`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES((SELECT gibbonModuleID FROM gibbonModule WHERE name='Messenger'), 'New Message_mailingList', 0, 'Manage Messages', 'Enable users to send messages to mailing lists.', 'messenger_post.php', 'messenger_post.php', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N');end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES ('001', (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Messenger' AND gibbonAction.name='New Message_mailingList'));end
ALTER TABLE gibbonMessengerTarget CHANGE `type` `type` enum('Class','Course','Form Group','Year Group','Activity','Role','Applicants','Individuals','Houses','Role Category','Transport','Attendance','Group','Mailing List') DEFAULT NULL;end
ALTER TABLE gibbonMessengerReceipt CHANGE `targetType` `targetType` enum('Class','Course','Form Group','Year Group','Activity','Role','Applicants','Individuals','Houses','Role Category','Transport','Attendance','Group','Mailing List') DEFAULT NULL;end
CREATE TABLE `gibbonActivityCategory` (`gibbonActivityCategoryID` INT(8) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,`gibbonSchoolYearID` INT(3) UNSIGNED ZEROFILL NOT NULL,`name` VARCHAR(90) NOT NULL,`nameShort` VARCHAR(12) NOT NULL,`description` TEXT NULL,`active` ENUM('Y','N') NOT NULL DEFAULT 'N',`signUpChoices` INT(3) NOT NULL DEFAULT 3,`viewableDate` DATETIME NULL,`accessOpenDate` DATETIME NULL,`accessCloseDate` DATETIME NULL,`accessEnrolmentDate` DATETIME NULL,`backgroundImage` TEXT NULL,PRIMARY KEY (`gibbonActivityCategoryID`),UNIQUE KEY (`name`, `gibbonSchoolYearID`)) ENGINE=InnoDB CHARSET=utf8 COLLATE=utf8_general_ci;end
CREATE TABLE `gibbonActivityChoice` (`gibbonActivityChoiceID` INT(12) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,`gibbonActivityCategoryID` INT(8) UNSIGNED ZEROFILL NOT NULL,`gibbonActivityID` INT(8) UNSIGNED ZEROFILL NOT NULL,`gibbonPersonID` INT(10) UNSIGNED ZEROFILL NOT NULL,`choice` INT(2) NOT NULL DEFAULT 1,`timestampCreated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,`timestampModified` TIMESTAMP NULL,`gibbonPersonIDCreated` INT(10) UNSIGNED ZEROFILL NOT NULL,`gibbonPersonIDModified` INT(10) UNSIGNED ZEROFILL NOT NULL,PRIMARY KEY (`gibbonActivityChoiceID`),UNIQUE KEY (`gibbonPersonID`, `choice`, `gibbonActivityCategoryID`)) ENGINE=InnoDB CHARSET=utf8 COLLATE=utf8_general_ci;end
CREATE TABLE `gibbonActivityPhoto` (`gibbonActivityPhotoID` INT(12) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,`gibbonActivityID` INT(8) UNSIGNED ZEROFILL NOT NULL,`filePath` VARCHAR(255) NOT NULL,`caption` VARCHAR(120) NOT NULL,`sequenceNumber` INT(6) NOT NULL,PRIMARY KEY (`gibbonActivityPhotoID`)) ENGINE=InnoDB CHARSET=utf8 COLLATE=utf8_general_ci;end
ALTER TABLE `gibbonActivity`  ADD `gibbonActivityCategoryID` INT(8) UNSIGNED ZEROFILL NULL AFTER `gibbonSchoolYearID`;end
INSERT INTO `gibbonAction` (`gibbonModuleID`, `name`, `precedence`, `category`, `description`, `helpURL`, `URLList`, `entryURL`, `entrySidebar`, `menuShow`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES((SELECT gibbonModuleID FROM gibbonModule WHERE name='Activities'), 'Explore Activities', 0, 'Activities', 'Allows users to explore available activities.', NULL, 'explore.php,explore_category.php,explore_activity.php', 'explore.php', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y');end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES ('001', (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Activities' AND gibbonAction.name='Explore Activities'));end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES ('002', (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Activities' AND gibbonAction.name='Explore Activities'));end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES ('004', (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Activities' AND gibbonAction.name='Explore Activities'));end
UPDATE `gibbonModule` SET `entryURL`='explore.php' WHERE name='Activities';end
ALTER TABLE `gibbonActivityCategory` ADD `sequenceNumber` INT(6) NOT NULL AFTER `backgroundImage`;end
INSERT INTO `gibbonAction` (`gibbonModuleID`, `name`, `precedence`, `category`, `description`, `helpURL`, `URLList`, `entryURL`, `entrySidebar`, `menuShow`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES((SELECT gibbonModuleID FROM gibbonModule WHERE name='Activities'), 'Manage Categories', 0, 'Administration', 'Allows users to manage activity categories.', NULL, 'activities_categories.php,activities_categories_add.php,activities_categories_edit.php,activities_categories_delete.php', 'activities_categories.php', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N');end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES ('001', (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Activities' AND gibbonAction.name='Manage Categories'));end
INSERT INTO `gibbonAction` (`gibbonModuleID`, `name`, `precedence`, `category`, `description`, `helpURL`, `URLList`, `entryURL`, `entrySidebar`, `menuShow`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES((SELECT gibbonModuleID FROM gibbonModule WHERE name='Activities'), 'Explore Activities_studentRegister', 1, 'Activities', 'Allows students to view activities and register', NULL, 'explore.php,explore_category.php,explore_activity.php,explore_activity_signUp.php', 'explore.php', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'Y', 'N', 'N');end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES ('003', (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Activities' AND gibbonAction.name='Explore Activities_studentRegister'));end
INSERT INTO `gibbonAction` (`gibbonActionID`, `gibbonModuleID`, `name`, `precedence`, `category`, `description`, `URLList`, `entryURL`, `entrySidebar`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES (NULL, (SELECT gibbonModuleID FROM gibbonModule WHERE name='Activities'), 'Manage Choices', 0, 'Enrolment', 'Manage student choices for activities.', 'choices_manage.php,choices_manage_generate.php,choices_manage_addEdit.php,choices_manage_delete.php','choices_manage.php', 'Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N');end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES (001, (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Activities' AND gibbonAction.name='Manage Choices'));end
ALTER TABLE `gibbonActivityStudent` ADD `gibbonActivityChoiceID` INT(12) UNSIGNED ZEROFILL NULL AFTER `gibbonFinanceInvoiceID`;end
INSERT INTO `gibbonAction` (`gibbonActionID`, `gibbonModuleID`, `name`, `precedence`, `category`, `description`, `URLList`, `entryURL`, `entrySidebar`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES (NULL, (SELECT gibbonModuleID FROM gibbonModule WHERE name='Activities'), 'Manage Enrolment', 0, 'Enrolment', 'Manage student enrolment for activities.', 'enrolment_manage.php','enrolment_manage.php', 'N', 'Y', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N');end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES (001, (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Activities' AND gibbonAction.name='Manage Enrolment'));end
INSERT INTO `gibbonAction` (`gibbonActionID`, `gibbonModuleID`, `name`, `precedence`, `category`, `description`, `URLList`, `entryURL`, `entrySidebar`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES (NULL, (SELECT gibbonModuleID FROM gibbonModule WHERE name='Activities'), 'Activities Overview', 0, 'Reports', 'View summary enrolment information for all activities in the current year.', 'report_overview.php','report_overview.php', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'Y', 'N', 'N', 'N');end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES (001, (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Activities' AND gibbonAction.name='Activities Overview'));end
INSERT INTO `gibbonAction` (`gibbonActionID`, `gibbonModuleID`, `name`, `precedence`, `category`, `description`, `URLList`, `entryURL`, `entrySidebar`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES (NULL, (SELECT gibbonModuleID FROM gibbonModule WHERE name='Activities'), 'Students Not Enrolled', 0, 'Enrolment', 'Print participant lists', 'report_notEnrolled.php','report_notEnrolled.php', 'Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N');end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES (001, (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Activities' AND gibbonAction.name='Students Not Enrolled'));end
INSERT INTO `gibbonAction` (`gibbonActionID`, `gibbonModuleID`, `name`, `precedence`, `category`, `description`, `URLList`, `entryURL`, `entrySidebar`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES (NULL, (SELECT gibbonModuleID FROM gibbonModule WHERE name='Activities'), 'Students Not Signed Up', 0, 'Enrolment', 'Print participant lists', 'report_notSignedUp.php','report_notSignedUp.php', 'Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N');end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES (001, (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Activities' AND gibbonAction.name='Students Not Signed Up'));end
INSERT INTO `gibbonAction` (`gibbonActionID`, `gibbonModuleID`, `name`, `precedence`, `category`, `description`, `URLList`, `entryURL`, `entrySidebar`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES (NULL, (SELECT gibbonModuleID FROM gibbonModule WHERE name='Activities'), 'View Unassigned Staff', 0, 'Enrolment', 'Print participant lists', 'report_unassigned.php','report_unassigned.php', 'Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N');end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES (001, (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Activities' AND gibbonAction.name='View Unassigned Staff'));end
INSERT INTO `gibbonAction` (`gibbonActionID`, `gibbonModuleID`, `name`, `precedence`, `category`, `description`, `URLList`, `entryURL`, `entrySidebar`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES (NULL, (SELECT gibbonModuleID FROM gibbonModule WHERE name='Activities'), 'Manage Staffing', 0, 'Enrolment', 'Allows users to assign staff to activities', 'enrolment_manage_staffing.php','enrolment_manage_staffing.php', 'N', 'Y', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N');end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES (001, (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Activities' AND gibbonAction.name='Manage Staffing'));end
INSERT INTO `gibbonAction` (`gibbonActionID`, `gibbonModuleID`, `name`, `precedence`, `category`, `description`, `URLList`, `entryURL`, `entrySidebar`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES (NULL, (SELECT gibbonModuleID FROM gibbonModule WHERE name='Activities'), 'View Activities_myChildren', 1, 'Activities', 'Allows parents to view activities for their children', 'activities_view_myChildren.php,activities_view_full.php','activities_view_myChildren.php', 'Y', 'N', 'N', 'N', 'Y', 'N', 'N', 'N', 'Y', 'N');end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES (004, (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Activities' AND gibbonAction.name='View Activities_myChildren'));end
ALTER TABLE gibbonMessengerReceipt ADD `unsubscribeKey` varchar(50) DEFAULT NULL AFTER `nameListStudent`;end
UPDATE gibbonAction SET `URLList`='mailingListRecipients_manage.php, mailingListRecipients_manage_add.php, mailingListRecipients_manage_edit.php, mailingListRecipients_manage_delete.php' WHERE name='Manage Mailing List Recipients' AND gibbonModuleID=(SELECT gibbonModuleID FROM gibbonModule WHERE name='Messenger');end
INSERT INTO `gibbonAction` (`gibbonModuleID`, `name`, `precedence`, `category`, `description`, `helpURL`, `URLList`, `entryURL`, `entrySidebar`, `menuShow`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES ((SELECT gibbonModuleID FROM gibbonModule WHERE name='Behaviour'), 'View Behaviour Records_myself', '0', 'Behaviour Records', 'View basic details of behaviour records about themselves.', 'teachers/people/behaviour/', 'behaviour_view.php,behaviour_view_details.php', 'behaviour_view.php', 'Y', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'Y', 'N', 'N');end
ALTER TABLE `gibbonStaff` ADD `coverageExclude` ENUM('N','Y') NOT NULL DEFAULT 'N' AFTER `biographicalGroupingPriority`;end
ALTER TABLE `gibbonStaff` ADD `coveragePriority` INT(1) DEFAULT 0 AFTER `coverageExclude`;end
";

//v28.0.01
++$count;
$sql[$count][0] = '28.0.01';
$sql[$count][1] = "";

//v29.0.00
++$count;
$sql[$count][0] = '29.0.00';
$sql[$count][1] = "
CREATE TABLE `gibbonFinancePettyCash` (`gibbonFinancePettyCashID` INT(12) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT , `gibbonSchoolYearID` VARCHAR(3) NOT NULL , `gibbonPersonID` INT(10) NOT NULL , `amount` DECIMAL(12,2) NOT NULL , `reason` VARCHAR(90) NULL , `notes` TEXT NULL , `gibbonPersonIDCreated` INT(10) NULL , `timestampCreated` TIMESTAMP NULL , `actionRequired` VARCHAR(60) NULL , `gibbonPersonIDStatus` INT(10) NULL , `timestampStatus` TIMESTAMP NULL , `status` VARCHAR(60) NOT NULL , PRIMARY KEY (`gibbonFinancePettyCashID`)) ENGINE = InnoDB CHARSET=utf8 COLLATE=utf8_general_ci;end
INSERT INTO `gibbonAction` (`gibbonActionID`, `gibbonModuleID`, `name`, `precedence`, `category`, `description`, `URLList`, `entryURL`, `entrySidebar`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES (NULL, (SELECT gibbonModuleID FROM gibbonModule WHERE name='Finance'), 'Petty Cash', 0, 'Expenses', 'Allows users to track basic payments and refunds of petty cash.', 'pettyCash.php,pettyCash_addEdit.php,pettyCash_delete.php,pettyCash_action.php','pettyCash.php', 'Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N');end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES (001, (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Finance' AND gibbonAction.name='Petty Cash'));end
INSERT INTO `gibbonSetting` (`scope`, `name`, `nameDisplay`, `description`, `value`) VALUES ('Finance', 'pettyCashReasons', 'Petty Cash Reasons', 'A comma-separated list.', 'Lunch Money,Small Purchase,Other');end
INSERT INTO `gibbonSetting` (`scope`, `name`, `nameDisplay`, `description`, `value`) VALUES ('Finance', 'pettyCashDefaultAction', 'Default Action Required', '', 'None');end
INSERT INTO `gibbonEmailTemplate` (`gibbonEmailTemplateID`, `type`, `templateType`, `moduleName`, `templateName`, `templateSubject`, `templateBody`, `variables`, `timestamp`) VALUES (NULL, 'Core', 'Student Petty Cash', 'Finance', 'Student Petty Cash', 'Notice of Petty Cash Balance', '<p>Dear {{parentTitle}} {{parentPreferredName}} {{parentSurname}},</p>\r\n<p>This is a notice to let you know that {{studentPreferredName}} has a petty cash balance of <strong>{{amount}}</strong>. Please help us to remind them to repay this amount to the school.</p>\r\n<p>This is an automated message. Please contact {{organisationEmail}} with any questions.</p>', '{\r\n\"parentEmail\": [\"safeEmail\"], \r\n\"date\": [\"date\"],\r\n\"amount\": [\"randomFloat\", 2, 10, 100],\r\n\"studentPreferredName\": [\"firstName\"],\r\n\"studentSurname\": [\"lastName\"],\r\n\"studentOfficialName\": [\"name\"],\r\n\"parentTitle\": [\"titleFemale\"],\r\n\"parentPreferredName\": [\"firstNameFemale\"],\r\n\"parentSurname\": [\"lastName\"],\r\n\"organisationEmail\": [\"safeEmail\"],\r\n\"organisationName\": [\"name\"]\r\n}', '2025-01-24 09:30:16');end
INSERT INTO `gibbonEmailTemplate` (`gibbonEmailTemplateID`, `type`, `templateType`, `moduleName`, `templateName`, `templateSubject`, `templateBody`, `variables`, `timestamp`) VALUES (NULL, 'Core', 'Staff Petty Cash', 'Finance', 'Staff Petty Cash', 'Notice of Petty Cash Balance', '<p>Dear {{preferredName}},</p>\r\n<p>This is a notice to let you know that you have a petty cash balance of <strong>{{amount}}</strong>. Please help us to repay this amount at your earliest convenience.</p>\r\n<p>This is an automated message. Please contact {{organisationEmail}} with any questions.</p>', '{\r\n\"email\": [\"safeEmail\"], \r\n\"date\": [\"date\"],\r\n\"amount\": [\"randomFloat\", 2, 10, 100],\r\n\"title\": [\"titleFemale\"],\r\n\"preferredName\": [\"firstName\"],\r\n\"surname\": [\"lastName\"],\r\n\"organisationEmail\": [\"safeEmail\"],\r\n\"organisationName\": [\"name\"]\r\n}', '2025-01-24 09:30:16');end
INSERT INTO `gibbonNotificationEvent` (`event`, `moduleName`, `actionName`, `type`, `scopes`, `active`) VALUES ('Petty Cash Notification', 'Finance', 'Petty Cash', 'Core', 'All', 'Y');end
ALTER TABLE `gibbonMarkbookColumn` ADD `columnColor` VARCHAR(7) NULL DEFAULT NULL AFTER `description`;end
UPDATE `gibbonCountry` SET `iddCountryCode` = '242' WHERE `printable_name` = 'Congo';end
UPDATE `gibbonCountry` SET `iddCountryCode` = '243' WHERE `printable_name` = 'Congo, the Democratic Republic of the';end
UPDATE `gibbonCountry` SET `iddCountryCode` = '246' WHERE `printable_name` = 'British Indian Ocean Territory';end
UPDATE `gibbonCountry` SET `iddCountryCode` = '673' WHERE `printable_name` = 'Brunei Darussalam';end
UPDATE `gibbonCountry` SET `iddCountryCode` = '225' WHERE `printable_name` = 'Cote D\'Ivoire';end
UPDATE `gibbonCountry` SET `iddCountryCode` = '500' WHERE `printable_name` = 'Falkland Islands (Malvinas)';end
UPDATE `gibbonCountry` SET `iddCountryCode` = '594' WHERE `printable_name` = 'French Guiana';end
UPDATE `gibbonCountry` SET `iddCountryCode` = '590' WHERE `printable_name` = 'Guadeloupe';end
UPDATE `gibbonCountry` SET `iddCountryCode` = '39' WHERE `printable_name` = 'Holy See (Vatican City State)';end
UPDATE `gibbonCountry` SET `iddCountryCode` = '98' WHERE `printable_name` = 'Iran, Islamic Republic of';end
UPDATE `gibbonCountry` SET `iddCountryCode` = '389' WHERE `printable_name` = 'Macedonia, the Former Yugoslav Republic of';end
UPDATE `gibbonCountry` SET `iddCountryCode` = '596' WHERE `printable_name` = 'Martinique';end
UPDATE `gibbonCountry` SET `iddCountryCode` = '691' WHERE `printable_name` = 'Micronesia, Federated States of';end
UPDATE `gibbonCountry` SET `iddCountryCode` = '373' WHERE `printable_name` = 'Moldova, Republic of';end
UPDATE `gibbonCountry` SET `iddCountryCode` = '970' WHERE `printable_name` = 'Palestinian Territory, Occupied';end
UPDATE `gibbonCountry` SET `iddCountryCode` = '64' WHERE `printable_name` = 'Pitcairn';end
UPDATE `gibbonCountry` SET `iddCountryCode` = '262' WHERE `printable_name` = 'Reunion';end
UPDATE `gibbonCountry` SET `iddCountryCode` = '47' WHERE `printable_name` = 'Svalbard and Jan Mayen';end
UPDATE `gibbonCountry` SET `iddCountryCode` = '963' WHERE `printable_name` = 'Syrian Arab Republic';end
UPDATE `gibbonCountry` SET `iddCountryCode` = '255' WHERE `printable_name` = 'Tanzania, United Republic of';end
UPDATE `gibbonCountry` SET `iddCountryCode` = '1 284' WHERE `printable_name` = 'Virgin Islands, British';end
UPDATE `gibbonCountry` SET `iddCountryCode` = '1 340' WHERE `printable_name` = 'Virgin Islands, U.s.';end
UPDATE `gibbonCountry` SET `iddCountryCode` = '212' WHERE `printable_name` = 'Western Sahara';end
UPDATE `gibbonCountry` SET `iddCountryCode` = '212' WHERE `printable_name` = 'Western Sahara';end
UPDATE `gibbonCountry` SET `printable_name` = 'Serbia, Republic of', `iddCountryCode` = '381' WHERE `printable_name` = 'Serbia and Montenegro';end
INSERT INTO `gibbonCountry` (`printable_name`, `iddCountryCode`) VALUES ('Montenegro', '382');end
ALTER TABLE `gibbonBehaviour` CHANGE `type` `type` ENUM('Positive','Negative','Observation') NOT NULL;end
INSERT INTO `gibbonSetting` (`scope`, `name`, `nameDisplay`, `description`, `value`) VALUES ('Behaviour', 'observationDescriptors', 'Observation Descriptors', 'Allowable choices for observation behaviour', '');end
INSERT INTO `gibbonNotificationEvent` (`event`, `moduleName`, `actionName`, `type`, `scopes`, `active`) VALUES ('New Observation Record', 'Behaviour', 'View Behaviour Records_all', 'Core', 'All,gibbonPersonIDStudent,gibbonYearGroupID', 'Y');end
INSERT INTO `gibbonSetting` (`scope`, `name`, `nameDisplay`, `description`, `value`) VALUES ('Application Form', 'successMessage', 'Success Message', 'Customised text to display when an application is succesfully submitted', 'Your application was successfully submitted. Please read the information in the green box above the application form for additional information.');end
ALTER TABLE `gibbonReportPrototypeSection` ADD `active` ENUM('Y','N') NOT NULL DEFAULT 'Y' AFTER `category`;end
ALTER TABLE `gibbonSpace` ADD `bookable` ENUM('Y','N') NOT NULL DEFAULT 'Y' AFTER `active`;end
ALTER TABLE `gibbonPerson` ADD `preferences` TEXT NULL AFTER `cookieConsent`;end
ALTER TABLE `gibbonMessengerReceipt` ADD INDEX `duplicateCheck` (`gibbonMessengerID`, `gibbonPersonID`) USING BTREE;end
ALTER TABLE `gibbonFamily` ADD `fields` TEXT NULL AFTER `familySync`;end
";

//v30.0.00
++$count;
$sql[$count][0] = '30.0.00';
$sql[$count][1] = "
ALTER TABLE `gibbonReportPrototypeSection` ADD `gibbonPersonIDLastEdit` INT(10) UNSIGNED ZEROFILL NULL;end
ALTER TABLE `gibbonReportPrototypeSection` ADD `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;end
UPDATE gibbonSetting SET nameDisplay='Catalyst License Organisation Name', description='Name of organisation on your Catalyst License' WHERE nameDisplay='gibbonedu.com Organisation Name';end
UPDATE gibbonSetting SET nameDisplay='Catalyst License Key', description='Organisation\'s private key, as registered on your Catalyst License' WHERE nameDisplay='gibbonedu.com Organisation Key';end
INSERT INTO `gibbonSetting` (`scope`, `name`, `nameDisplay`, `description`, `value`) VALUES ('Staff', 'staffDutyTypes', 'Staff Duty Types', 'A comma-separated list.', 'Supervision,Other');end
ALTER TABLE `gibbonStaffDuty` ADD `type` VARCHAR(40) NOT NULL DEFAULT 'Other' AFTER `nameShort`;end
INSERT INTO `gibbonAction` (`gibbonModuleID`, `name`, `precedence`, `category`, `description`, `helpURL`, `URLList`, `entryURL`, `entrySidebar`, `menuShow`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES((SELECT gibbonModuleID FROM gibbonModule WHERE name='Activities'), 'Explore Activities_registerByParent', 2, 'Activities', 'Allows parents to view activities and register for their children', NULL, 'explore.php,explore_category.php,explore_activity.php,explore_activity_signUp.php', 'explore.php', 'Y', 'Y', 'N', 'N', 'N', 'Y', 'N', 'N', 'N', 'Y', 'N');end
ALTER TABLE `gibbonActivityCategory` ADD `gibbonYearGroupIDParentRegister` VARCHAR(255) NULL AFTER `accessEnrolmentDate`;end
INSERT INTO `gibbonModule` (`gibbonModuleID`, `name`, `description`, `entryURL`, `type`, `active`, `category`, `version`, `author`, `url`) VALUES (NULL, 'Alerts', 'View, create and manage alerts for students', 'studentAlerts_manage.php', 'Core', 'Y', 'Pastoral', '', 'Gibbon Foundation', 'https://gibbonedu.org');end
CREATE TABLE `gibbonAlert` (`gibbonAlertID` INT(12) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT, `gibbonSchoolYearID` INT(3) UNSIGNED ZEROFILL NOT NULL, `gibbonPersonID` INT(10) UNSIGNED ZEROFILL NOT NULL, `gibbonAlertLevelID` INT(3) UNSIGNED ZEROFILL NULL, `context` ENUM('Automatic','Manual') NOT NULL DEFAULT 'Automatic', `type` VARCHAR(60) NOT NULL, `status` ENUM('Pending','Approved','Declined') NOT NULL DEFAULT 'Pending', `level` VARCHAR(60) NULL, `dateStart` DATE NULL, `dateEnd` DATE NULL, `comment` TEXT NULL, `timestampCreated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `gibbonPersonIDCreator` INT(10) UNSIGNED ZEROFILL NULL, `gibbonPersonIDApproval` int(10) UNSIGNED ZEROFILL DEFAULT NULL, `notesApproval` TEXT NULL, `timestampApproval` timestamp NULL DEFAULT NULL, PRIMARY KEY (`gibbonAlertID`)) ENGINE = InnoDB CHARSET=utf8;end
INSERT INTO `gibbonAction` (`gibbonActionID`, `gibbonModuleID`, `name`, `precedence`, `category`, `description`, `URLList`, `entryURL`, `entrySidebar`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES (NULL, (SELECT gibbonModuleID FROM gibbonModule WHERE name='Alerts'), 'Manage Student Alerts_my', 0, 'Alerts', 'Manage, create and edit alerts for students.', 'studentAlerts_manage.php,studentAlerts_add.php, studentAlerts_edit.php,studentAlerts_manage_view.php','studentAlerts_manage.php', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'Y', 'N', 'N', 'N');end
INSERT INTO `gibbonAction` (`gibbonActionID`, `gibbonModuleID`, `name`, `precedence`, `category`, `description`, `URLList`, `entryURL`, `entrySidebar`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES (NULL, (SELECT gibbonModuleID FROM gibbonModule WHERE name='Alerts'), 'Manage Student Alerts_all', 1, 'Alerts', 'Manage, create, edit and approve all student alerts.', 'studentAlerts_manage.php,studentAlerts_add.php,studentAlerts_edit.php,studentAlerts_manage_approval.php,studentAlerts_manage_view.php','studentAlerts_manage.php','Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N');end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES (001, (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Alerts' AND gibbonAction.name='Manage Student Alerts_all'));end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES (001, (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Alerts' AND gibbonAction.name='Manage Student Alerts_my'));end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES (002, (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Alerts' AND gibbonAction.name='Manage Student Alerts_my'));end
UPDATE `gibbonAction` SET name='Manage Alert Types and Levels' WHERE name='Manage Alert Levels' AND gibbonModuleID=(SELECT gibbonModuleID FROM gibbonModule WHERE name='School Admin');end
CREATE TABLE `gibbonAlertType` (`gibbonAlertTypeID` INT(6) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT, `name` VARCHAR(60) NOT NULL, `tag` VARCHAR(5) NULL, `active` ENUM('Y','N') NOT NULL DEFAULT 'Y', `color` VARCHAR(10) NULL COMMENT 'RGB Hex, leading #', `colorBG` VARCHAR(10) NULL COMMENT 'RGB Hex, leading #', `description` TEXT NULL, `gibbonPersonIDCreator` INT(10) UNSIGNED ZEROFILL NULL, `timestampCreated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`gibbonAlertTypeID`)) ENGINE = InnoDB CHARSET=utf8;end
UPDATE `gibbonSetting` SET value=REPLACE(value,'Admin,','Admin,Pastoral,') WHERE name='mainMenuCategoryOrder';end
UPDATE `gibbonModule` SET category='Pastoral' WHERE name='Behaviour' OR name='Attendance' OR name='Individual Needs';end
ALTER TABLE `gibbonAlertType` ADD `type` enum('Core','Additional') NOT NULL DEFAULT 'Additional' AFTER `active`;end
ALTER TABLE `gibbonAlertType` ADD `sequenceNumber` INT(6) NOT NULL AFTER `description`;end
ALTER TABLE `gibbonAlert` ADD `gibbonAlertTypeID` INT(6) UNSIGNED ZEROFILL NOT NULL AFTER `gibbonAlertLevelID`;end
ALTER TABLE `gibbonActivity` ADD `paymentDescription` TEXT NULL AFTER `paymentFirmness`;end
INSERT INTO `gibbonAlertType` (`name`, `tag`, `active`, `type`, `color`, `colorBG`, `description`, `sequenceNumber`, `gibbonPersonIDCreator`, `timestampCreated`) VALUES ('Individual Needs', 'IN', 'Y', 'Core', NULL, NULL, 'Indicates that a student has an Individual Needs record. Automatic alerts are created based on the highest level of Individual Needs descriptor for that student.', 3, NULL, CURRENT_TIMESTAMP), ('Academic', 'A', 'Y', 'Core', NULL, NULL, 'Indicates a level of academic concern for a given student. Automatic alerts are created from Markbook Entries that have an Attainment or Effort value below the Lowest Acceptable value of that grade scale.', 1, NULL, CURRENT_TIMESTAMP), ('Behaviour', 'B', 'Y', 'Core', NULL, NULL, 'Indicates a level of behavioural concern for a given student. Automatic alerts are created from Behaviour Reports when the number of reports exceeds a given threshold.', 2, NULL, CURRENT_TIMESTAMP), ('Medical', 'M', 'Y', 'Core', NULL, NULL, 'Indicates the presence of one or more Medical Conditions. Automatic alerts are created based on the highest level of Medical Condition for that student.', 4, NULL, CURRENT_TIMESTAMP), ('Privacy', 'P', 'Y', 'Core', '#939090', '#dddddd', 'Indicates a student with a Privacy concern. Automatic alerts are created based on the presence of any Privacy option in the student data.', 5, NULL, CURRENT_TIMESTAMP);end
UPDATE `gibbonAction` SET `precedence`=2 WHERE name='Manage Student Alerts_all';end
INSERT INTO `gibbonAction` (`gibbonActionID`, `gibbonModuleID`, `name`, `precedence`, `category`, `description`, `URLList`, `entryURL`, `entrySidebar`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES (NULL, (SELECT gibbonModuleID FROM gibbonModule WHERE name='Alerts'), 'Manage Student Alerts_headOfYear', 1, 'Alerts', 'Manage, create, edit and approve all alerts for a given year group.', 'studentAlerts_manage.php,studentAlerts_add.php,studentAlerts_edit.php,studentAlerts_manage_approval.php,studentAlerts_manage_view.php','studentAlerts_manage.php','Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N');end
UPDATE `gibbonAction` SET name='Student Alert Settings' WHERE name='Manage Alert Types and Levels' AND gibbonModuleID=(SELECT gibbonModuleID FROM gibbonModule WHERE name='School Admin');end
UPDATE `gibbonModule` SET name='Student Alerts' WHERE name='Alerts' AND type='Core';end
ALTER TABLE `gibbonAlertType` ADD `useLevels` ENUM('Y','N') NOT NULL DEFAULT 'Y' AFTER `active`;end
ALTER TABLE `gibbonAlert` ADD INDEX(`gibbonSchoolYearID`, `gibbonPersonID`);end
ALTER TABLE `gibbonAlertType` ADD `thresholdLow` INT NULL AFTER `description`, ADD `thresholdMed` INT NULL AFTER `thresholdLow`, ADD `thresholdHigh` INT NULL AFTER `thresholdMed`;end
UPDATE `gibbonAlertType` SET `useLevels`='N',color='#ec4899',colorBG='#f9a8d4' WHERE name='Privacy';end
UPDATE `gibbonAlertType` SET `thresholdLow`=(SELECT IFNULL(value,3) FROM gibbonSetting WHERE name='academicAlertLowThreshold' LIMIT 1),thresholdMed=(SELECT IFNULL(value,5) FROM gibbonSetting WHERE name='academicAlertMediumThreshold' LIMIT 1),thresholdHigh=(SELECT IFNULL(value,9) FROM gibbonSetting WHERE name='academicAlertHighThreshold' LIMIT 1) WHERE name='Academic';end
UPDATE `gibbonAlertType` SET `thresholdLow`=(SELECT IFNULL(value,3) FROM gibbonSetting WHERE name='behaviourAlertLowThreshold' LIMIT 1),thresholdMed=(SELECT IFNULL(value,5) FROM gibbonSetting WHERE name='behaviourAlertMediumThreshold' LIMIT 1),thresholdHigh=(SELECT IFNULL(value,9) FROM gibbonSetting WHERE name='behaviourAlertHighThreshold' LIMIT 1) WHERE name='Behaviour';end
DELETE FROM `gibbonSetting` WHERE `name` LIKE '%Alert%Threshold' AND scope='User Admin';end
INSERT INTO `gibbonEmailTemplate` (`gibbonEmailTemplateID`, `type`, `templateType`, `moduleName`, `templateName`, `templateSubject`, `templateBody`, `variables`) VALUES (NULL, 'Core', 'Parent Notification for Student Lending Item', 'Library', 'Parent Notification for Student Lending Item', 'Notice of Student Lending Item', '<p>Dear {{preferredName}},</p>\r\n<p>This is a notice to let you know that {{studentPreferredName}} has recently borrowed an item from the library. Please return the item according to the return date.</p>\r\n<p>This is an automated message. Please contact {{organisationEmail}} with any questions.</p>', '{\r\n\"parentEmail\": [\"safeEmail\"], \r\n\"date\": [\"date\"],\r\n\"amount\": [\"randomFloat\", 2, 10, 100],\r\n\"studentPreferredName\": [\"firstName\"],\r\n\"studentSurname\": [\"lastName\"],\r\n\"studentOfficialName\": [\"name\"],\r\n\"parentTitle\": [\"titleFemale\"],\r\n\"parentPreferredName\": [\"firstNameFemale\"],\r\n\"parentSurname\": [\"lastName\"],\r\n\"organisationEmail\": [\"safeEmail\"],\r\n\"organisationName\": [\"name\"]\r\n}');end
CREATE TABLE `gibbonPersonPhoto` (`gibbonPersonPhotoID` INT(12) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT, `gibbonSchoolYearID` INT(3) UNSIGNED ZEROFILL NOT NULL,`gibbonPersonID` INT(10) UNSIGNED ZEROFILL NOT NULL, `personImage` varchar(255) NOT NULL, `gibbonPersonIDCreated` INT(10) DEFAULT NULL, `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`gibbonPersonPhotoID`), UNIQUE KEY (`gibbonPersonID`,`gibbonSchoolYearID`)) ENGINE = InnoDB;end
INSERT INTO `gibbonAction` (`gibbonActionID`, `gibbonModuleID`, `name`, `precedence`, `category`, `description`, `URLList`, `entryURL`, `entrySidebar`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES (NULL, (SELECT gibbonModuleID FROM gibbonModule WHERE name='Student Alerts'), 'Student Alerts by Form Group', 0, 'Reports', 'View all alerts for a given form group.', 'report_alertsByFormGroup.php','report_alertsByFormGroup.php','Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N');end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES (001, (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Student Alerts' AND gibbonAction.name='Student Alerts by Form Group'));end
INSERT INTO `gibbonModule` (`name`, `description`, `entryURL`, `type`, `active`, `category`, `version`, `author`, `url`) VALUES ('Calendar', 'View and manage school events on a shared calendar.', 'calendar_view.php', 'Core', 'Y', 'Other', '', 'Gibbon Foundation', 'https://gibbonedu.org');end
INSERT INTO `gibbonAction` (`gibbonModuleID`, `name`, `precedence`, `category`, `description`, `helpURL`, `URLList`, `entryURL`, `entrySidebar`, `menuShow`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES ((SELECT gibbonModuleID FROM gibbonModule WHERE name='Calendar'), 'View Calendar_all', '1', 'Calendar', 'View a calendar of school dates and events.', '', 'calendar_view.php', 'calendar_view.php', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'Y', 'Y', 'Y', 'Y');end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES (001, (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Calendar' AND gibbonAction.name='View Calendar_all'));end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES (002, (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Calendar' AND gibbonAction.name='View Calendar_all'));end
INSERT INTO `gibbonAction` (`gibbonModuleID`, `name`, `precedence`, `category`, `description`, `helpURL`, `URLList`, `entryURL`, `entrySidebar`, `menuShow`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES ((SELECT gibbonModuleID FROM gibbonModule WHERE name='Calendar'), 'Manage Calendars_all', '1', 'Administration', 'Enables users to add and edit events on any calendar.', '', 'calendar_manage.php,calendar_manage_addEdit.php,calendar_manage_delete.php,calendar_manage_types.php', 'calendar_manage.php', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N');end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES (001, (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Calendar' AND gibbonAction.name='Manage Calendars_all'));end
CREATE TABLE `gibbonCalendar` (`gibbonCalendarID` INT(6) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT, `gibbonSchoolYearID` INT(3) UNSIGNED ZEROFILL NOT NULL, `name` VARCHAR(60) NOT NULL, `description` VARCHAR(255) NULL, `summary` TEXT NULL, `color` VARCHAR(7) NULL, `public` ENUM('N','Y') NOT NULL DEFAULT 'N', `viewableStaff` ENUM('N','Y') NOT NULL DEFAULT 'N', `viewableStudents` ENUM('N','Y') NOT NULL DEFAULT 'N', `viewableParents` ENUM('N','Y') NOT NULL DEFAULT 'N', `viewableOther` ENUM('N','Y') NOT NULL DEFAULT 'N', `sequenceNumber` INT(8) NOT NULL, PRIMARY KEY (`gibbonCalendarID`)) ENGINE = InnoDB  CHARSET=utf8;end
CREATE TABLE `gibbonCalendarEditor` (`gibbonCalendarEditorID` INT(10) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT , `gibbonCalendarID` INT(6) UNSIGNED ZEROFILL NOT NULL , `gibbonPersonID` INT(10) UNSIGNED ZEROFILL NOT NULL , `editAllEvents` ENUM('N','Y') NOT NULL DEFAULT 'N' , PRIMARY KEY (`gibbonCalendarEditorID`)) ENGINE = InnoDB CHARSET=utf8;end
CREATE TABLE `gibbonCalendarEventType` (`gibbonCalendarEventTypeID` INT(6) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT , `type` VARCHAR(60) NOT NULL , `color` VARCHAR(7) NOT NULL , `sequenceNumber` INT(3) NOT NULL , PRIMARY KEY (`gibbonCalendarEventTypeID`)) ENGINE = InnoDB CHARSET=utf8;end
CREATE TABLE `gibbonCalendarEvent` (`gibbonCalendarEventID` INT(12) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT , `gibbonCalendarID` INT(6) UNSIGNED ZEROFILL NOT NULL , `gibbonCalendarEventTypeID` INT(6) UNSIGNED ZEROFILL NOT NULL , `name` VARCHAR(120) NOT NULL , `description` TEXT NULL , `status` ENUM('Confirmed','Tentative','Cancelled') NOT NULL DEFAULT 'Confirmed' , `allDay` ENUM('N','Y') NOT NULL DEFAULT 'N' , `dateStart` DATE NOT NULL , `dateEnd` DATE NOT NULL , `timeStart` TIME NULL , `timeEnd` TIME NULL , `locationType` ENUM('Internal','External') NOT NULL DEFAULT 'External' , `locationDetail` VARCHAR(255) NULL , `locationURL` VARCHAR(255) NULL , `gibbonSpaceID` INT(10) UNSIGNED ZEROFILL NULL , `foreignTable` VARCHAR(60) NULL , `foreignTableID` INT(12) UNSIGNED ZEROFILL NULL , `timestampCreated` TIMESTAMP NULL , `timestampModified` TIMESTAMP NULL , `gibbonPersonIDCreated` INT(10) UNSIGNED ZEROFILL NOT NULL , `gibbonPersonIDModified` INT(10) UNSIGNED ZEROFILL NOT NULL , `gibbonPersonIDOrganiser` INT(10) UNSIGNED ZEROFILL NOT NULL , PRIMARY KEY (`gibbonCalendarEventID`)) ENGINE = InnoDB CHARSET=utf8;end
CREATE TABLE `gibbonCalendarEventPerson` (`gibbonCalendarEventPersonID` INT(12) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT , `gibbonCalendarEventID` INT(12) UNSIGNED ZEROFILL NOT NULL , `gibbonPersonID` INT(10) UNSIGNED ZEROFILL NOT NULL , `role` ENUM('Attendee','Organiser', 'Coach', 'Assistant', 'Other') NOT NULL DEFAULT 'Attendee', `timestampCreated` TIMESTAMP NULL, `timestampModified` TIMESTAMP NULL , `gibbonPersonIDCreated` INT(10) UNSIGNED ZEROFILL NOT NULL, `gibbonPersonIDModified` INT(10) UNSIGNED ZEROFILL NOT NULL , PRIMARY KEY (`gibbonCalendarEventPersonID`), UNIQUE KEY (`gibbonCalendarEventID`, `gibbonPersonID`) ) ENGINE = InnoDB CHARSET=utf8;end
INSERT INTO `gibbonAction` (`gibbonModuleID`, `name`, `precedence`, `category`, `description`, `helpURL`, `URLList`, `entryURL`, `entrySidebar`, `menuShow`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES ((SELECT gibbonModuleID FROM gibbonModule WHERE name='Calendar'), 'Manage Events_all', '1', 'Administration', 'Manage, create and edit all Calendar events.', '', 'calendar_event_manage.php, calendar_event_add.php, calendar_event_edit.php, calendar_event_delete.php, calendar_event_view.php, calendar_event_enrolment.php, calendar_event_enrolment_add.php, calendar_event_enrolment_delete.php', 'calendar_event_manage.php', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N');end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES (001, (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Calendar' AND gibbonAction.name='Manage Events_all'));end
INSERT INTO `gibbonAction` (`gibbonModuleID`, `name`, `precedence`, `category`, `description`, `helpURL`, `URLList`, `entryURL`, `entrySidebar`, `menuShow`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES((SELECT gibbonModuleID FROM gibbonModule WHERE name='Calendar'), 'Manage Events_my', 0, 'Administration', 'Allows users to create ands edit thier own calendar events.', '', 'calendar_event_manage.php, calendar_event_add.php, calendar_event_edit.php, calendar_event_view.php, calendar_event_enrolment.php, calendar_event_enrolment_add.php', 'calendar_event_manage.php', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'N', 'N', 'N');end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES (001, (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Calendar' AND gibbonAction.name='Manage Events_my'));end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES (002, (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Calendar' AND gibbonAction.name='Manage Events_my'));end
INSERT INTO `gibbonAction` (`gibbonActionID`, `gibbonModuleID`, `name`, `precedence`, `category`, `description`, `URLList`, `entryURL`, `entrySidebar`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES (NULL, (SELECT gibbonModuleID FROM gibbonModule WHERE name='Student Alerts'), 'Student Alerts by Class', 0, 'Reports', 'View all alerts for a given class.', 'report_alertsByClass.php','report_alertsByClass.php','Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N');end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES (001, (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Student Alerts' AND gibbonAction.name='Student Alerts by Class'));end
UPDATE `gibbonAction` SET URLList='studentAlerts_manage.php,studentAlerts_add.php,studentAlerts_edit.php,studentAlerts_delete.php,studentAlerts_manage_status.php,studentAlerts_manage_view.php' WHERE (name='Manage Student Alerts_headOfYear' OR name='Manage Student Alerts_all') AND gibbonModuleID=(SELECT gibbonModuleID FROM gibbonModule WHERE name='Student Alerts');end
ALTER TABLE `gibbonAlertType` ADD `adminOnly` enum('Y','N') NOT NULL DEFAULT 'Y' AFTER `active`;end
UPDATE `gibbonAlertType` SET adminOnly='N' WHERE name='Academic' OR name='Behaviour';end
INSERT INTO `gibbonNotificationEvent` (`event`, `moduleName`, `actionName`, `type`, `scopes`, `active`) VALUES ('Pending Student Alert', 'Student Alerts', 'Manage Student Alerts', 'Core', 'All,gibbonPersonIDStudent,gibbonYearGroupID', 'Y');end
INSERT INTO `gibbonNotificationEvent` (`event`, `moduleName`, `actionName`, `type`, `scopes`, `active`) VALUES ('New Student Alert', 'Student Alerts', 'Manage Student Alerts', 'Core', 'All,gibbonPersonIDStudent,gibbonYearGroupID', 'Y');end
ALTER TABLE `gibbonAlert` ADD `gibbonCourseClassID` INT(8) UNSIGNED ZEROFILL NULL AFTER `gibbonPersonID`;end
ALTER TABLE `gibbonAlert` CHANGE `status` `status` ENUM('Pending','Approved','Declined','Cancelled') NOT NULL DEFAULT 'Pending', CHANGE `gibbonPersonIDCreator` `gibbonPersonIDCreated` INT(10) UNSIGNED ZEROFILL NULL, CHANGE `gibbonPersonIDApproval` `gibbonPersonIDStatus` INT(10) UNSIGNED ZEROFILL DEFAULT NULL, CHANGE `notesApproval` `notesStatus` TEXT NULL, CHANGE `timestampApproval` `timestampStatus` timestamp NULL DEFAULT NULL;end
UPDATE `gibbonAction` SET URLList='studentAlerts_manage.php,studentAlerts_add.php,studentAlerts_edit.php,studentAlerts_manage_status.php,studentAlerts_manage_view.php' WHERE name='Manage Student Alerts_my' AND gibbonModuleID=(SELECT gibbonModuleID FROM gibbonModule WHERE name='Student Alerts');end
INSERT INTO `gibbonNotificationEvent` (`event`, `moduleName`, `actionName`, `type`, `scopes`, `active`) VALUES ('Updated Student Alert', 'Student Alerts', 'Manage Student Alerts', 'Core', 'All,gibbonPersonIDStudent,gibbonYearGroupID', 'Y');end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES (002, (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Student Alerts' AND gibbonAction.name='Student Alerts by Class'));end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES (002, (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='Student Alerts' AND gibbonAction.name='Student Alerts by Form Group'));end
ALTER TABLE `gibbonAlertType` ADD `automatic` enum('Y','N') NOT NULL DEFAULT 'N' AFTER `active`;end
UPDATE `gibbonAlertType` SET `automatic`='Y' WHERE type='Core';end
UPDATE `gibbonNotificationEvent` SET event='New Global Alert' WHERE event='New Student Alert' AND moduleName='Student Alerts';end
INSERT INTO `gibbonNotificationEvent` (`event`, `moduleName`, `actionName`, `type`, `scopes`, `active`) VALUES ('New Class Alert', 'Student Alerts', 'Manage Student Alerts', 'Core', 'All,gibbonPersonIDStudent,gibbonYearGroupID', 'Y');end
INSERT IGNORE INTO `gibbonLanguage` (`gibbonLanguageID`, `name`) VALUES (NULL, 'Balochi');end
INSERT INTO `gibbonAction` (`gibbonModuleID`, `name`, `precedence`, `category`, `description`, `URLList`, `entryURL`, `entrySidebar`, `menuShow`, `defaultPermissionAdmin`, `defaultPermissionTeacher`, `defaultPermissionStudent`, `defaultPermissionParent`, `defaultPermissionSupport`, `categoryPermissionStaff`, `categoryPermissionStudent`, `categoryPermissionParent`, `categoryPermissionOther`) VALUES((SELECT gibbonModuleID FROM gibbonModule WHERE name='System Admin'), 'Impersonate User', 0, 'Utilities', '', 'impersonateUser.php', 'impersonateUser.php', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N');end
INSERT INTO `gibbonPermission` (`gibbonRoleID` ,`gibbonActionID`) VALUES ('001', (SELECT gibbonActionID FROM gibbonAction JOIN gibbonModule ON (gibbonAction.gibbonModuleID=gibbonModule.gibbonModuleID) WHERE gibbonModule.name='System Admin' AND gibbonAction.name='Impersonate User'));end
UPDATE `gibboni18n` SET `active` = 'Y',`version` = '30.0.00',`installed` = 'Y'  WHERE `code` = 'ja_JP';end
UPDATE `gibboni18n` SET `active` = 'Y',`version` = '30.0.00',`installed` = 'Y'  WHERE `code` = 'pt_PT';end
UPDATE `gibbonSetting` SET value=REPLACE(value,',Pastoral,Pastoral,',',Pastoral,') WHERE name='mainMenuCategoryOrder';end
ALTER TABLE `gibbonPersonMedical` CHANGE `longTermMedication` `longTermMedication` ENUM('','Y','N') NOT NULL DEFAULT 'N';end
SELECT NULL;end
SELECT NULL;end
SELECT NULL;end
SELECT NULL;end
SELECT NULL;end
INSERT INTO `gibbonLibraryType` (`name`, `active`, `fields`) VALUES ('Digital Publication', 'Y', '[{\"name\":\"URL Link\",\"description\":\"Paste the url link of the digital publication\",\"type\":\"Text\",\"options\":\"\",\"default\":\"\",\"required\":\"Y\"}]');end
UPDATE `gibbonAction` SET URLList='calendar_manage.php,calendar_manage_addEdit.php,calendar_manage_delete.php,calendar_eventTypes_manage.php, calendar_eventTypes_manage_addEdit.php' WHERE name='Manage Calendars_all' AND gibbonModuleID=(SELECT gibbonModuleID FROM gibbonModule WHERE name='Calendar');end
UPDATE `gibbonAction` SET URLList='calendar_event_manage.php, calendar_event_add.php, calendar_event_edit.php, calendar_event_delete.php, calendar_event_view.php, calendar_event_enrolment.php, calendar_event_enrolment_add.php, calendar_event_enrolment_edit.php' WHERE (name='Manage Events_all' OR name='Manage Events_my') AND gibbonModuleID=(SELECT gibbonModuleID FROM gibbonModule WHERE name='Calendar');end
INSERT INTO `gibboni18n` (`code`, `name`, `version`, `active`, `installed`, `systemDefault`, `dateFormat`, `dateFormatRegEx`, `dateFormatPHP`, `rtl`) VALUES ('ca_CA', 'Català - Catalonia', '30.0.00', 'Y', 'N', 'N', 'dd/mm/yyyy', '/^(0[1-9]|[12][0-9]|3[01])[- /.](0[1-9]|1[012])[- /.](19|20)\\d\\d$/i', 'd/m/Y', 'N');end
UPDATE `gibbonAction` SET description='Allows users to create and edit thier own calendar events.' WHERE name='Manage Events_my' AND gibbonModuleID=(SELECT gibbonModuleID FROM gibbonModule WHERE name='Calendar');end
UPDATE `gibbonAction` SET URLList='calendar_event_manage.php, calendar_event_add.php, calendar_event_edit.php, calendar_event_delete.php, calendar_event_view.php, calendar_event_participants.php, calendar_event_participants_add.php, calendar_event_participants_edit.php, calendar_event_participants_delete.php' WHERE (name='Manage Events_all' OR name='Manage Events_my') AND gibbonModuleID=(SELECT gibbonModuleID FROM gibbonModule WHERE name='Calendar');end
ALTER TABLE `gibbonPerson` CHANGE `username` `username` VARCHAR(40) NULL DEFAULT NULL;end
ALTER TABLE `gibbonCourse` CHANGE `nameShort` `nameShort` VARCHAR(16) NOT NULL;end
ALTER TABLE `gibbonCourseClass` CHANGE `nameShort` `nameShort` VARCHAR(16) NOT NULL;end
ALTER TABLE `gibbonSchoolYearSpecialDay` ADD `cancelDuty` ENUM('Y','N') DEFAULT 'N' NULL AFTER `cancelActivities`;end
ALTER TABLE `gibbonSchoolYearSpecialDay` ADD `cancelBookings` ENUM('Y','N') DEFAULT 'N' NULL AFTER `cancelDuty`;end
ALTER TABLE `gibbonSchoolYearSpecialDay` ADD `cancelClasses` ENUM('Y','N') DEFAULT 'N' NULL AFTER `cancelBookings`;end
INSERT INTO `gibbonCalendarEventType` (`type`, `color`, `sequenceNumber`) VALUES ('School Event', '', 0), ('Meeting', '', 1);end
ALTER TABLE `gibbonCalendar` ADD `editableStaff` ENUM('Y','N') DEFAULT 'N' NULL AFTER `viewableOther`;end
ALTER TABLE `gibbonCalendar` ADD `viewableParticipants` ENUM('Y','N') DEFAULT 'N' NULL AFTER `viewableOther`;end
UPDATE `gibbonAction` SET name='View Calendar' WHERE name='View Calendar_all' AND gibbonModuleID=(SELECT gibbonModuleID FROM gibbonModule WHERE name='Calendar');end
UPDATE `gibbonFormField` SET `fieldGroup`='Miscellaneous' WHERE `fieldGroup`='AdmissionsFields' AND `gibbonFormField`.`fieldName` = 'howDidYouHear';end
UPDATE `gibbonFormField` SET `fieldGroup`='MiscellaneousFields' WHERE `fieldGroup`='Miscellaneous' AND `gibbonFormField`.`fieldName` = 'howDidYouHear';end
ALTER TABLE `gibbonCalendarEventType` CHANGE `color` `color` VARCHAR(7) NULL, CHANGE `sequenceNumber` `sequenceNumber` INT(3) NOT NULL DEFAULT 0;end

";

//v31.0.00
++$count;
$sql[$count][0] = '31.0.00';
$sql[$count][1] = "
UPDATE `gibbonSetting` SET value='br[style|class],strong[style|class],b[style|class],em[style|class],span[style|class],p[style|class],address[style|class],pre[style|class],h1[style|class],h2[style|class],h3[style|class],h4[style|class],h5[style|class],h6[style|class],table[style|class],thead[style|class],tbody[style|class],tfoot[style|class],tr[style|class],td[style|class|colspan|rowspan],ol[style|class],ul[style|class],li[style|class],blockquote[style|class],a[style|class|target|href|data-fileupload|data-fileid],img[style|class|src|width|height],video[style|class],source[style|class],hr[style|class],iframe[style|class|width|height|src|frameborder|allowfullscreen],embed[style|class],div[style|class],sup[style|class],sub[style|class],code[style|class],details[style|class],summary[style|class],pagebreak,columnbreak' WHERE name='allowableHTML';end
";
