#!/bin/sh
set -e

# xdebug setup
if [ -n "$DEBUG" ]; then
    echo "Debug mode enabled"
    # Install xdebug PECL extension
    pecl install xdebug
    CONTAINER_IP=`/sbin/ip route|awk '/default/ { print $3 }'`
    cat << EOF > $PHP_INI_DIR/conf.d/debug.ini
zend_extension=xdebug.so

xdebug.cli_color = 1
xdebug.client_host=${CONTAINER_IP}
xdebug.log_level=0
xdebug.mode=develop,debug
xdebug.show_error_trace = On
xdebug.start_with_request=yes
xdebug.var_display_max_children = 128
xdebug.var_display_max_data = 128
xdebug.var_display_max_depth = 8

max_execution_time=600
EOF
else
    echo "Debug mode not enabled"
fi

if [ -n "$MYSQL_HOST" ] && [ -n "$MYSQL_USER" ] && [ -n "$MYSQL_PASSWORD" ] && [ -n "$MYSQL_DATABASE" ]; then
    if [ ! -e "config.php" ]; then
        echo "File config.php does not exists, Configuring instance with environment variables"        
        cat resources/templates/installer/config.twig.html | twig -p databaseServer="$MYSQL_HOST" -p databaseName="$MYSQL_DATABASE" > config.php
        rm -Rf installer
    fi
    unset MYSQL_HOST MYSQL_USER MYSQL_PASSWORD MYSQL_DATABASE 

sh docker-php-entrypoint "$@"
