# Dockerfile.gibbon
FROM php:8.2-apache

# Install required extensions and Composer
RUN apt-get update && apt-get install -y \
    unzip zip git curl wget pkg-config \
    libicu-dev libgettextpo-dev \
    libpng-dev libjpeg-dev libfreetype6-dev \
    libzip-dev zlib1g-dev \
    netcat-openbsd default-mysql-client \
 && docker-php-ext-install intl gettext gd zip pdo_mysql \
 && a2enmod rewrite \
 && curl -sS https://getcomposer.org/installer | php && \
    mv composer.phar /usr/local/bin/composer

# Set working dir and Apache root
WORKDIR /var/www/html
#RUN sed -i 's|/var/www/html|/var/www/gibbon|g' /etc/apache2/sites-available/000-default.conf

# Download and extract Gibbon v29
RUN wget https://github.com/GibbonEdu/core/archive/refs/tags/v29.0.00.zip && \
    unzip v29.0.00.zip && \
    mv core-29.0.00/* . && \
    rm -rf core-29.0.00 v29.0.00.zip

# Install PHP dependencies
RUN composer install --no-dev --optimize-autoloader

# Ensure session and cache folders exist and are writable
RUN mkdir -p /var/www/html/uploads/tmp \
    && mkdir -p /var/www/html/uploads/cache \
    && chmod -R 0777 /var/www/html/uploads \
    && chmod -R 0777 /var/www/html/uploads/tmp /var/www/html/uploads/cache

#  Set custom PHP session save path (prevents session_start warnings)
RUN echo "session.save_path = /var/www/html/uploads/tmp" > /usr/local/etc/php/conf.d/session.ini
RUN printf '<VirtualHost *:80>\n\
    DocumentRoot /var/www/html\n\
    <Directory /var/www/html>\n\
        AllowOverride All\n\
        Require all granted\n\
    </Directory>\n\
</VirtualHost>\n' > /etc/apache2/sites-available/000-default.conf
# Keep Apache running in foreground
CMD ["apache2-foreground"]
