#gibbon-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gibbon-ingress
  namespace: gibbon-dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging   # keep staging for test
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-body-size: "64m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
spec:
  ingressClassName: nginx
  rules:
    - host: gibbon-dev.vanhoa.edu.vn 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gibbon-dev-service
                port:
                  number: 80
  tls:
    - hosts:
        - gibbon-dev.vanhoa.edu.vn
      secretName: gibbon-dev-tls


