# gibbon-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gibbon-app
  namespace: demo-app-deployment
  labels:
    app: gibbon
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gibbon
  template:
    metadata:
      labels:
        app: gibbon
    spec:
      nodeSelector:
          role: app-demo-1
        initialDelaySeconds: 15
        periodSeconds: 10
      initContainers:
        - name: init-gibbon-perms
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              echo "[Init] Removing config.php and setting uploads permissions..."
              mkdir -p /var/www/html/gibbon/uploads/tmp /var/www/html/gibbon/uploads/cache
              chmod -R 0777 /var/www/html/gibbon/uploads
          volumeMounts:
            - name: uploads
              mountPath: /var/www/html/gibbon/uploads
              readOnly: false
      containers:
        - name: gibbon
          image: ntony3419/gibbon:v29-fix-path
          imagePullPolicy: Always
          readinessProbe:            # ✅ belongs under the container
            httpGet:
              path: /
              port: 80
          ports:
            - containerPort: 80
          volumeMounts:
            - name: uploads
              mountPath: /var/www/html/gibbon/uploads
              readOnly: false
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "chmod -R 0777 /var/www/html/gibbon/uploads"]
          env:
            - name: DB_HOST
              value: gibbon-mysql.demo-app-deployment.svc.cluster.local
            - name: DB_NAME
              value: gibbon
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: gibbon-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gibbon-db-secret
                  key: password
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: gibbon-uploads-pvc
---
# ---------------------------
# ClusterIP Service for Gibbon Web App
# ---------------------------
apiVersion: v1
kind: Service
metadata:
  name: gibbon-service
  namespace: demo-app-deployment
spec:
  selector:
    app: gibbon
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
# -----------------
# PersistentVoume
# -----------------
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gibbon-uploads-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  nfs:
    server: 10.1.0.5
    path: /mnt/k8s-database-and-storage/gibbon-files
---
# ---------------------------
# PersistentVolumeClaim
# ---------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gibbon-uploads-pvc
  namespace: demo-app-deployment
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs
