#gibbon-db-init-configmap.yaml 
apiVersion: v1
kind: ConfigMap
metadata:
  name: gibbon-db-init
  namespace: demo-app-deployment
data:
  init.sql: |
    GRANT ALL PRIVILEGES ON gibbon.* TO 'gibbonuser'@'%' IDENTIFIED BY 'gibbonpass123';
    FLUSH PRIVILEGES;
