apiVersion: apps/v1
kind: Deployment
metadata:
  name: gibbon-mysql
  namespace: demo-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gibbon-mysql
  template:
    metadata:
      labels:
        app: gibbon-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_DATABASE
              value: gibbon
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gibbon-db-secret
                  key: password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: gibbon-db-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gibbon-db-secret
                  key: password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: gibbon-mysql-pvc
