apiVersion: batch/v1
kind: Job
metadata:
  name: gibbon-mysql-fix-grant
  namespace: demo-app-deployment
spec:
  template:
    spec:
      containers:
        - name: grant-access
          image: mysql:5.7
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Waiting for DB...";
              until mysql -h gibbon-mysql.demo-app-deployment.svc.cluster.local -u root -p$MYSQL_ROOT_PASSWORD -e "SELECT 1"; do
                sleep 5
              done
              echo "Applying GRANT...";
              mysql -h gibbon-mysql.demo-app-deployment.svc.cluster.local -u root -p$MYSQL_ROOT_PASSWORD -e "GRANT ALL PRIVILEGES ON gibbon.* TO 'gibbonuser'@'%' IDENTIFIED BY '$MYSQL_PASSWORD'; FLUSH PRIVILEGES;";
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gibbon-db-secret
                  key: password
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gibbon-db-secret
                  key: password
      restartPolicy: OnFailure
