#gibbon-mysql-pv-pvc.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gibbon-mysql-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  nfs:
    server: 10.1.0.5
    path: /mnt/k8s-database-and-storage/gibbon-mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gibbon-mysql-pvc
  namespace: demo-app-deployment
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs
