apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gibbon-ingress
  namespace: demo-app-deployment
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: banthach.vanhoa.edu.vn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gibbon
                port:
                  number: 80
  tls:
    - hosts:
        - banthach.vanhoa.edu.vn
      secretName: gibbon-tls
