apiVersion: v1
kind: Secret
metadata:
  name: gibbon-demo-db-secret
  namespace: gibbon-demo-deploy
type: Opaque
stringData:
  # app secret used by php code specially in db.php (maybe other location use it too)
  DB_HOST: gibbon-demo-mysql.gibbon-demo-deploy.svc.cluster.local
  DB_PORT: "3306"
  DB_NAME: gibbon
  DB_USER: gibbonuser
  DB_PASSWORD: gibbonpass123   # db.php also support DB_Pass
  DB_PASS: gibbonpass123
  DB_CHARSET: utf8mb4

  # MySQL server side keys 
  username: gibbonuser         # used by MYSQL_USER in mysql Deployment
  password: gibbonpass123      # used by MYSQL_PASSWORD & MYSQL_ROOT_PASSWORD
