name: Development Discussion
description: Suggest an idea for this project
title: 'Discussion: '
labels:
  - discussion

body:
  - type: markdown
    attributes:
      value: |
        Be sure to check out our contributor docs if you haven't already.
        https://github.com/GibbonEdu/core/blob/master/docs/CONTRIBUTING.md#how-to-submit-a-pull-request

        To request new features, please use the Feature Requests category in our support forums.
        https://ask.gibbonedu.org/categories/feature-requests

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Is your development discussion related to a problem?
      placeholder: I\'m always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Please describe in detail what you're suggesting to change or improve.
      placeholder: To solve the problem, I think we should [...]
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe alternatives you've considered
      placeholder: Let us know of any alternative solutions or features you've considered.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the discussion here
