<?php
/*
Gibbon, Flexible & Open School System
Copyright (C) 2010, Ross Parker

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.

Certain code below was taken from the PHPExcel examples, which are licensed under the GNU GPL.
*/

@session_start() ;

//System includes
include "../../config.php" ;
include "../../functions.php" ;
include "../../version.php" ;

//New PDO DB connection
try {
  	$connection2=new PDO("mysql:host=$databaseServer;dbname=$databaseName;charset=utf8", $databaseUsername, $databasePassword);
	$connection2->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
	$connection2->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
}
catch(PDOException $e) {
  echo $e->getMessage();
}

//Module includes
include "./moduleFunctions.php" ;

if (isActionAccessible($guid, $connection2, "/modules/Tracking/dataPoints.php")==FALSE) {
	//Acess denied
	print "<div class='error'>" ;
		print _("You do not have access to this action.") ;
	print "</div>" ;
}
else {
	/** Include PHPExcel */
	require_once $_SESSION[$guid]["absolutePath"] . '/lib/PHPExcel/Classes/PHPExcel.php';

	// Create new PHPExcel object
	$excel = new PHPExcel();

	//Create border style for use locale_filter_matches
	$style_border= array('borders' => array('right' => array('style' => PHPExcel_Style_Border::BORDER_THIN,'color' => array('argb' => '766f6e'),), 'left' => array('style' => PHPExcel_Style_Border::BORDER_THIN,'color' => array('argb' => '766f6e'),), 'top' => array('style' => PHPExcel_Style_Border::BORDER_THIN,'color' => array('argb' => '766f6e'),), 'bottom' => array('style' => PHPExcel_Style_Border::BORDER_THIN,'color' => array('argb' => '766f6e'),)));
	$style_head_fill=array('fill' => array('type' => PHPExcel_Style_Fill::FILL_SOLID, 'color' => array('rgb' => 'B89FE2'))) ;

	// Set document properties
	$excel->getProperties()->setCreator(formatName("",$_SESSION[$guid]["preferredName"], $_SESSION[$guid]["surname"], "Staff"))
		 ->setLastModifiedBy(formatName("",$_SESSION[$guid]["preferredName"], $_SESSION[$guid]["surname"], "Staff"))
		 ->setTitle(_('Assessment Data Points'))
		 ->setDescription(_('This information is confidential. Generated by Gibbon (https://gibbonedu.org).')) ;


	 //Get and check settings
 	$externalAssessmentDataPoints=unserialize(getSettingByScope($connection2, "Tracking", "externalAssessmentDataPoints")) ;
 	$internalAssessmentDataPoints=unserialize(getSettingByScope($connection2, "Tracking", "internalAssessmentDataPoints")) ;
	$internalAssessmentTypes=explode(",", getSettingByScope($connection2, "Formal Assessment", "internalAssessmentTypes")) ;
 	if (count($externalAssessmentDataPoints)==0 AND count($internalAssessmentDataPoints)==0) { //Seems like things are not configured, so show error
		$excel->setActiveSheetIndex(0) ->setCellValue('A1', _('An error has occurred.')) ;
 	}
 	else { //Seems like things are configured, so proceed


		//Get year groups and create sheets
		$yearGroups=getYearGroups($connection2) ;
		if ($yearGroups=="") {
			$excel->setActiveSheetIndex(0)->setCellValue('A1', _('An error has occurred.')) ;
		}
		else {
			for ($i=0; $i<count($yearGroups); $i=$i+2) {
				//SET UP SHEET WITH HEADERS ETC
				$activeRow=2 ;
				if ($i>0) {
					$excel->createSheet(); //Create sheet
				}
				$excel->setActiveSheetIndex($i/2) ;
				$excel->getActiveSheet()->setTitle(_($yearGroups[($i+1)])) ; //Rename sheet
				$excel->getActiveSheet()
					->setCellValue('A1', _('Username'))
					->setCellValue('B1', _('Surname'))
				   ->setCellValue('C1', _('Preferred Name'))
				   ->setCellValue('D1', _('DOB'))
				   ->setCellValue('E1', _('Roll Group'))
				   ->setCellValue('F1', _('Status'));
				foreach(range('A','F') as $columnID) {
					$excel->getActiveSheet()->getStyle($columnID . "1")->applyFromArray($style_border);
					$excel->getActiveSheet()->getStyle($columnID . "1")->applyFromArray($style_head_fill) ;
					$excel->getActiveSheet()->getColumnDimension($columnID)->setAutoSize(true);
				}

				//GET ASSESSMENTS AND CREATE HEADERS
				try {
					$where="" ;
					$data=array("gibbonSchoolYearID"=>$_SESSION[$guid]["gibbonSchoolYearID"], "gibbonYearGroupID"=>$yearGroups[$i]);
					$typeCount=0 ;
					foreach ($internalAssessmentTypes AS $type) {
						//Check if type included for this year group
						$include=FALSE ;
						foreach ($internalAssessmentDataPoints AS $point) {
							if ($point["type"]==$type) {
								if (!(strpos($point["gibbonYearGroupIDList"],$yearGroups[$i])===FALSE)) {
									$include=TRUE ;
								}
							}
						}
						if ($include==TRUE) {
							$data["type" . $typeCount]=$type ;
							$where.="type=:type" . $typeCount . " AND " ;
							$typeCount++ ;
						}
					}

					$sql="" ;
					//$sql="SELECT surname, preferredName, username, dob, nameShort AS rollgroup, status FROM gibbonPerson JOIN gibbonStudentEnrolment ON (gibbonStudentEnrolment.gibbonPersonID = gibbonPerson.gibbonPersonID) JOIN gibbonRollGroup ON (gibbonStudentEnrolment.gibbonRollGroupID = gibbonRollGroup.gibbonRollGroupID) WHERE (status='Full' OR status='Left') AND gibbonStudentEnrolment.gibbonSchoolYearID=:gibbonSchoolYearID AND gibbonYearGroupID=:gibbonYearGroupID ORDER BY status, surname, preferredName" ;
					$result=$connection2->prepare($sql);
					$result->execute($data);
				}
				catch(PDOException $e) {
					$excel->getActiveSheet()
						->setCellValue('A2', _("Your request failed due to a database error.")) ;
				}
				if ($result->rowCount()<1) {
					$excel->getActiveSheet()
						->setCellValue('A2', _("There are no records to display.")) ;
				}
				else {
					while ($row=$result->fetch()) {

					}
				}


				//GET STUDENTS AND LIST THEIR DETAILS
				try {
					$data=array("gibbonSchoolYearID"=>$_SESSION[$guid]["gibbonSchoolYearID"], "gibbonYearGroupID"=>$yearGroups[$i]);
					$sql="SELECT surname, preferredName, username, dob, nameShort AS rollgroup, status FROM gibbonPerson JOIN gibbonStudentEnrolment ON (gibbonStudentEnrolment.gibbonPersonID = gibbonPerson.gibbonPersonID) JOIN gibbonRollGroup ON (gibbonStudentEnrolment.gibbonRollGroupID = gibbonRollGroup.gibbonRollGroupID) WHERE (status='Full' OR status='Left') AND gibbonStudentEnrolment.gibbonSchoolYearID=:gibbonSchoolYearID AND gibbonYearGroupID=:gibbonYearGroupID ORDER BY status, surname, preferredName" ;
					$result=$connection2->prepare($sql);
					$result->execute($data);
				}
				catch(PDOException $e) {
					$excel->getActiveSheet()
						->setCellValue('A2', _("Your request failed due to a database error.")) ;
				}
				if ($result->rowCount()<1) {
					$excel->getActiveSheet()
						->setCellValue('A2', _("There are no records to display.")) ;
				}
				else {
					while ($row=$result->fetch()) {
						$excel->getActiveSheet()
							->setCellValue('A' . $activeRow, $row["username"])
							->setCellValue('B' . $activeRow, $row["surname"])
							->setCellValue('C' . $activeRow, $row["preferredName"])
							->setCellValue('D' . $activeRow, dateConvertBack($guid, $row["dob"]))
							->setCellValue('E' . $activeRow, $row["rollgroup"])
							->setCellValue('F' . $activeRow, $row["status"]) ;
						$excel->getActiveSheet()->getStyle('A' . $activeRow)->applyFromArray($style_border);
						$excel->getActiveSheet()->getStyle('B' . $activeRow)->applyFromArray($style_border);
						$excel->getActiveSheet()->getStyle('C' . $activeRow)->applyFromArray($style_border);
						$excel->getActiveSheet()->getStyle('D' . $activeRow)->applyFromArray($style_border);
						$excel->getActiveSheet()->getStyle('E' . $activeRow)->applyFromArray($style_border);
						$excel->getActiveSheet()->getStyle('F' . $activeRow)->applyFromArray($style_border);
						$activeRow++ ;
					}
				}
			}
		}
	}





	//FINALISE THE DOCUMENT SO IT IS READY FOR DOWNLOAD
	// Set active sheet index to the first sheet, so Excel opens this as the first sheet
	$excel->setActiveSheetIndex(0);

	// Redirect output to a client’s web browser (Excel2007)
	header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
	header('Content-Disposition: attachment;filename="Data Points.xlsx"');
	header('Cache-Control: max-age=0');
	// If you're serving to IE 9, then the following may be needed
	header('Cache-Control: max-age=1');

	// If you're serving to IE over SSL, then the following may be needed
	header ('Expires: Mon, 26 Jul 1997 05:00:00 GMT'); // Date in the past
	header ('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT'); // always modified
	header ('Cache-Control: cache, must-revalidate'); // HTTP/1.1
	header ('Pragma: public'); // HTTP/1.0

	$objWriter = PHPExcel_IOFactory::createWriter($excel, 'Excel2007');
	$objWriter->save('php://output');
	exit;
}
?>
