<?php
/*
Gibbon, Flexible & Open School System
Copyright (C) 2010, Ross Parker

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

namespace Gibbon\Tables\Renderer;

use Gibbon\Domain\DataSet;
use Gibbon\Tables\DataTable;
use Gibbon\Tables\Columns\Column;
use Gibbon\Tables\Renderer\RendererInterface;

/**
 * SpreadsheetRenderer
 *
 * @version v16
 * @since   v16
 */
class SpreadsheetRenderer implements RendererInterface
{
    protected $path;

    public function __construct($absolutePath)
    {
        if (!class_exists('PHPExcel')) {
            require_once $absolutePath . '/lib/PHPExcel/Classes/PHPExcel.php';
        }
    }

    /**
     * Render the table to a spreadsheet file: xlsx, xls, csv
     *
     * @param DataTable $table
     * @param DataSet $dataSet
     * @return string
     */
    public function renderTable(DataTable $table, DataSet $dataSet)
    {
        // Create new PHPExcel object
        $excel = new \PHPExcel();

        // Create styles
        $headerStyle = [
            'fill' => [
                'type' => \PHPExcel_Style_Fill::FILL_SOLID, 
                'color' => ['rgb' => 'eeeeee'],
            ],
            'borders' => [
                'top' => ['style' => \PHPExcel_Style_Border::BORDER_THIN, 'color' => ['argb' => '444444'], ], 
                'bottom' => ['style' => \PHPExcel_Style_Border::BORDER_THIN, 'color' => ['argb' => '444444'], ],
            ],
            'font' => [
                'size' => 12,
                'bold' => true,
            ],
            'alignment' => [
                'vertical' => \PHPExcel_Style_Alignment::VERTICAL_CENTER,
            ],
        ];
        $rowStyle = [
            'font' => [
                'size' => 12,
            ],
        ];

        // Set document properties
        $excel->getProperties()->setCreator($table->getMetaData('creator'))
            ->setLastModifiedBy($table->getMetaData('creator'))
            ->setTitle($table->getMetaData('name'))
            ->setDescription(__('This information is confidential. Generated by Gibbon (https://gibbonedu.org).')) ;

        $excel->setActiveSheetIndex(0) ;
        $sheet = $excel->getActiveSheet();

        if ($dataSet->count() == 0) {
            $sheet->setCellValue('A1', __('Your query has returned 0 rows.', 'Query Builder'));
            $sheet->getStyle('A1')->applyFromArray($rowStyle);
        } else {
            // HEADER ROW
            $rowCount = 1;
            $cellCount = 0;

            $sheet->getRowDimension($rowCount)->setRowHeight(24);

            foreach ($table->getColumns() as $columnName => $column) {
                $alpha = $this->num2alpha($cellCount);

                $sheet->setCellValue($alpha.$rowCount, $columnName);
                $sheet->getStyle($alpha.$rowCount)->applyFromArray($headerStyle);
                
                if ($column->getWidth() == 'auto') {
                    $sheet->getColumnDimension($alpha)->setAutoSize(true);
                } else {
                    $sheet->getColumnDimension($alpha)->setWidth($column->getWidth());
                }

                $cellCount++;
            }

            // TABLE ROWS
            $rowCount = 2;
            foreach ($dataSet as $data) {
                $sheet->getRowDimension($rowCount)->setRowHeight(20);

                // CELLS
                $cellCount = 0;
                foreach ($table->getColumns() as $columnName => $column) {
                    $alpha = $this->num2alpha($cellCount);

                    $sheet->setCellValue( $alpha.$rowCount, $column->getOutput($data));
                    $sheet->getStyle($alpha.$rowCount)->applyFromArray($rowStyle);

                    $cellCount++;
                }
                $rowCount++;
            }
        }

        $filename = $table->getMetaData('filename');
        $exportFileType = $table->getMetaData('filetype');
        if (empty($exportFileType)) $exportFileType = 'Excel2007';

        switch($exportFileType) {
            case 'Excel2007': 		$filename .= '.xlsx'; 
                                    $mimetype = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'; break;
            case 'Excel5': 			$filename .= '.xls';  
                                    $mimetype = 'application/vnd.ms-excel'; break;
            case 'OpenDocument': 	$filename .= '.ods';  
                                    $mimetype = 'application/vnd.oasis.opendocument.spreadsheet'; break;
            case 'CSV': 			$filename .= '.csv';  
                                    $mimetype = 'text/csv'; break;
        }

        // FINALIZE THE DOCUMENT SO IT IS READY FOR DOWNLOAD
        // Set active sheet index to the first sheet, so Excel opens this as the first sheet
        $excel->setActiveSheetIndex(0);

        // Redirect output to a client’s web browser (Excel2007)
        header('Content-Type: '.$mimetype);
        header('Content-Disposition: attachment;filename="'.$filename.'"');
        header('Cache-Control: max-age=1');

        // If you're serving to IE over SSL, then the following may be needed
        header ('Expires: Mon, 26 Jul 1997 05:00:00 GMT'); // Date in the past
        header ('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT'); // always modified
        header ('Cache-Control: cache, must-revalidate'); // HTTP/1.1
        header ('Pragma: public'); // HTTP/1.0

        $objWriter = \PHPExcel_IOFactory::createWriter($excel, $exportFileType);
        $objWriter->save('php://output');

        return;
    }

    protected function num2alpha($n)
    {
        for ($r = ''; $n >= 0; $n = intval($n / 26) - 1) {
            $r = chr($n % 26 + 0x41).$r;
        }
    
        return $r;
    }
}
