version: 1.0.00
countries:
    Afghanistan:
        idd: 93
    Albania:
        idd: 355
    Algeria:
        idd: 213
    American Samoa:
        idd: 1 684
    Andorra:
        idd: 376
    Angola:
        idd: 244
    Anguilla:
        idd: 1 264
    Antarctica:
        idd: 672
    Antigua and Barbuda:
        idd: 1 268
    Argentina:
        idd: 54
    Armenia:
        idd: 374
    Aruba:
        idd: 297
    Australia:
        idd: 61
    Austria:
        idd: 43
    Azerbaijan:
        idd: 994
    Bahamas:
        idd: 1 242
    Bahrain:
        idd: 973
    Bangladesh:
        idd: 880
    Barbados:
        idd: 1 246
    Belarus:
        idd: 375
    Belgium:
        idd: 32
    Belize:
        idd: 501
    Benin:
        idd: 229
    Bermuda:
        idd: 1 441
    Bhutan:
        idd: 975
    Bolivia:
        idd: 591
    Bosnia and Herzegovina:
        idd: 387
    Botswana:
        idd: 267
    Bouvet Island:
        idd: 
    Brazil:
        idd: 55
    British Indian Ocean Territory:
        idd: 
    Brunei Darussalam:
        idd: 
    Bulgaria:
        idd: 359
    Burkina Faso:
        idd: 226
    Burundi:
        idd: 257
    Cambodia:
        idd: 855
    Cameroon:
        idd: 237
    Canada:
        idd: 1
    Cape Verde:
        idd: 238
    Cayman Islands:
        idd: 1 345
    Central African Republic:
        idd: 236
    Chad:
        idd: 235
    Chile:
        idd: 56
    China:
        idd: 86
    Christmas Island:
        idd: 61
    Cocos (Keeling) Islands:
        idd: 61
    Colombia:
        idd: 57
    Comoros:
        idd: 269
    Congo:
        idd: 
    Congo, the Democratic Republic of the:
        idd: 
    Cook Islands:
        idd: 682
    Costa Rica:
        idd: 506
    Cote D''Ivoire:
        idd: 
    Croatia:
        idd: 385
    Cuba:
        idd: 53
    Cyprus:
        idd: 357
    Czech Republic:
        idd: 420
    Denmark:
        idd: 45
    Djibouti:
        idd: 253
    Dominica:
        idd: 1 767
    Dominican Republic:
        idd: 1 809
    Ecuador:
        idd: 593
    Egypt:
        idd: 20
    El Salvador:
        idd: 503
    Equatorial Guinea:
        idd: 240
    Eritrea:
        idd: 291
    Estonia:
        idd: 372
    Ethiopia:
        idd: 251
    Falkland Islands (Malvinas):
        idd: 
    Faroe Islands:
        idd: 298
    Fiji:
        idd: 679
    Finland:
        idd: 358
    France:
        idd: 33
    French Guiana:
        idd: 
    French Polynesia:
        idd: 689
    French Southern Territories:
        idd: 
    Gabon:
        idd: 241
    Gambia:
        idd: 220
    Georgia:
        idd: 995
    Germany:
        idd: 49
    Ghana:
        idd: 233
    Gibraltar:
        idd: 350
    Greece:
        idd: 30
    Greenland:
        idd: 299
    Grenada:
        idd: 1 473
    Guadeloupe:
        idd: 
    Guam:
        idd: 1 671
    Guatemala:
        idd: 502
    Guinea:
        idd: 224
    Guinea-Bissau:
        idd: 245
    Guyana:
        idd: 592
    Haiti:
        idd: 509
    Heard Island and Mcdonald Islands:
        idd: 
    Holy See (Vatican City State):
        idd: 
    Honduras:
        idd: 504
    Hong Kong:
        idd: 852
    Hungary:
        idd: 36
    Iceland:
        idd: 354
    India:
        idd: 91
    Indonesia:
        idd: 62
    Iran, Islamic Republic of:
        idd: 
    Iraq:
        idd: 964
    Ireland:
        idd: 353
    Israel:
        idd: 972
    Italy:
        idd: 39
    Jamaica:
        idd: 1 876
    Japan:
        idd: 81
    Jordan:
        idd: 962
    Kazakhstan:
        idd: 7
    Kenya:
        idd: 254
    Kiribati:
        idd: 686
    Korea, Democratic People''s Republic of:
        idd: 
    Korea, Republic of:
        idd: 
    Kuwait:
        idd: 965
    Kyrgyzstan:
        idd: 996
    Lao People''s Democratic Republic:
        idd: 
    Latvia:
        idd: 371
    Lebanon:
        idd: 961
    Lesotho:
        idd: 266
    Liberia:
        idd: 231
    Libyan Arab Jamahiriya:
        idd: 
    Liechtenstein:
        idd: 423
    Lithuania:
        idd: 370
    Luxembourg:
        idd: 352
    Macao:
        idd: 
    Macedonia, the Former Yugoslav Republic of:
        idd: 
    Madagascar:
        idd: 261
    Malawi:
        idd: 265
    Malaysia:
        idd: 60
    Maldives:
        idd: 960
    Mali:
        idd: 223
    Malta:
        idd: 356
    Marshall Islands:
        idd: 692
    Martinique:
        idd: 
    Mauritania:
        idd: 222
    Mauritius:
        idd: 230
    Mayotte:
        idd: 262
    Mexico:
        idd: 52
    Micronesia, Federated States of:
        idd: 
    Moldova, Republic of:
        idd: 
    Monaco:
        idd: 377
    Mongolia:
        idd: 976
    Montserrat:
        idd: 1 664
    Morocco:
        idd: 212
    Mozambique:
        idd: 258
    Myanmar:
        idd: 
    Namibia:
        idd: 264
    Nauru:
        idd: 674
    Nepal:
        idd: 977
    Netherlands:
        idd: 31
    Netherlands Antilles:
        idd: 599
    New Caledonia:
        idd: 687
    New Zealand:
        idd: 64
    Nicaragua:
        idd: 505
    Niger:
        idd: 227
    Nigeria:
        idd: 234
    Niue:
        idd: 683
    Norfolk Island:
        idd: 672
    Northern Mariana Islands:
        idd: 1 670
    Norway:
        idd: 47
    Oman:
        idd: 968
    Pakistan:
        idd: 92
    Palau:
        idd: 680
    Palestinian Territory, Occupied:
        idd: 
    Panama:
        idd: 507
    Papua New Guinea:
        idd: 675
    Paraguay:
        idd: 595
    Peru:
        idd: 51
    Philippines:
        idd: 63
    Pitcairn:
        idd: 
    Poland:
        idd: 48
    Portugal:
        idd: 351
    Puerto Rico:
        idd: 1
    Qatar:
        idd: 974
    Reunion:
        idd: 
    Romania:
        idd: 40
    Russian Federation:
        idd: 
    Rwanda:
        idd: 250
    Saint Helena:
        idd: 290
    Saint Kitts and Nevis:
        idd: 1 869
    Saint Lucia:
        idd: 1 758
    Saint Pierre and Miquelon:
        idd: 508
    Saint Vincent and the Grenadines:
        idd: 1 784
    Samoa:
        idd: 685
    San Marino:
        idd: 378
    Sao Tome and Principe:
        idd: 239
    Saudi Arabia:
        idd: 966
    Senegal:
        idd: 221
    Serbia and Montenegro:
        idd: 
    Seychelles:
        idd: 248
    Sierra Leone:
        idd: 232
    Singapore:
        idd: 65
    Slovakia:
        idd: 421
    Slovenia:
        idd: 386
    Solomon Islands:
        idd: 677
    Somalia:
        idd: 252
    South Africa:
        idd: 27
    South Georgia and the South Sandwich Islands:
        idd: 
    Spain:
        idd: 34
    Sri Lanka:
        idd: 94
    Sudan:
        idd: 249
    Suriname:
        idd: 597
    Svalbard and Jan Mayen:
        idd: 
    Swaziland:
        idd: 268
    Sweden:
        idd: 46
    Switzerland:
        idd: 41
    Syrian Arab Republic:
        idd: 
    Taiwan:
        idd: 886
    Tajikistan:
        idd: 992
    Tanzania, United Republic of:
        idd: 
    Thailand:
        idd: 66
    Timor-Leste:
        idd: 670
    Togo:
        idd: 228
    Tokelau:
        idd: 690
    Tonga:
        idd: 676
    Trinidad and Tobago:
        idd: 1 868
    Tunisia:
        idd: 216
    Turkey:
        idd: 90
    Turkmenistan:
        idd: 993
    Turks and Caicos Islands:
        idd: 1 649
    Tuvalu:
        idd: 688
    Uganda:
        idd: 256
    Ukraine:
        idd: 380
    United Arab Emirates:
        idd: 971
    United Kingdom:
        idd: 44
    United States:
        idd: 1
    United States Minor Outlying Islands:
        idd: 
    Uruguay:
        idd: 598
    Uzbekistan:
        idd: 998
    Vanuatu:
        idd: 678
    Venezuela:
        idd: 58
    Viet Nam:
        idd: 
    Virgin Islands, British:
        idd: 
    Virgin Islands, U.s.:
        idd: 
    Wallis and Futuna:
        idd: 681
    Western Sahara:
        idd: 
    Yemen:
        idd: 967
    Zambia:
        idd: 260
    Zimbabwe:
        idd: 263');
