# PHP MAiler details
Encoding: base64
CharSet: UTF-8
WordWrap: 65
# Use Google Server Send.
#IsSMTP: 1
#SMTPAuth: 1
#SMTPSecure: ssl
#Host: smtp.gmail.com
#Port: 465
#Username: username@gmail.com
#Password: yourepassword 