<?php
$I = new AcceptanceTester($scenario);
$I->wantTo('submit a student application form');

$I->amOnPage('/index.php?q=/modules/Students/applicationForm.php');

$I->seeBreadcrumb('Application Form');

$formValues = array(
    'surname'                     => 'McTest',
    'firstName'                   => '',
    'preferredName'               => '',
    'officialName'                => '',
    'nameInCharacters'            => '',
    'gender'                      => '',
    'dob'                         => '',
    'languageHomePrimary'         => '',
    'languageHomeSecondary'       => '',
    'languageFirst'               => '',
    'languageSecond'              => '',
    'languageThird'               => '',
    'countryOfBirth'              => '',
    'citizenship1'                => '',
    'citizenship1Passport'        => '',
    'nationalIDCardNumber'        => '',
    'residencyStatus'             => '',
    'visaExpiryDate'              => '',
    'email'                       => '',
    'phone1'                      => '',
    'phone1Type'                  => '',
    'phone1CountryCode'           => '',
    'phone2'                      => '',
    'phone2Type'                  => '',
    'phone2CountryCode'           => '',
    'sen'                         => '',
    'senDetails'                  => '',
    'medicalInformation'          => '',
    'gibbonSchoolYearIDEntry'     => '',
    'dateStart'                   => '',
    'gibbonYearGroupIDEntry'      => '',
    'schoolName1'                 => '',
    'schoolAddress1'              => '',
    'schoolGrades1'               => '',
    'schoolLanguage1'             => '',
    'schoolDate1'                 => '',
    'schoolName2'                 => '',
    'schoolAddress2'              => '',
    'schoolGrades2'               => '',
    'schoolLanguage2'             => '',
    'schoolDate2'                 => '',
    'homeAddress'                 => '',
    'homeAddressDistrict'         => '',
    'homeAddressCountry'          => '',
    'parent1title'                => '',
    'parent1surname'              => '',
    'parent1firstName'            => '',
    'parent1preferredName'        => '',
    'parent1officialName'         => '',
    'parent1nameInCharacters'     => '',
    'parent1gender'               => '',
    'parent1relationship'         => '',
    'parent1languageFirst'        => '',
    'parent1languageSecond'       => '',
    'parent1citizenship1'         => '',
    'parent1nationalIDCardNumber' => '',
    'parent1residencyStatus'      => '',
    'parent1visaExpiryDate'       => '',
    'parent1email'                => '',
    'parent1phone1'               => '',
    'parent1phone1Type'           => '',
    'parent1phone1CountryCode'    => '',
    'parent1phone2'               => '',
    'parent1phone2Type'           => '',
    'parent1phone2CountryCode'    => '',
    'parent1profession'           => '',
    'parent1employer'             => '',
    'secondParent'                => 'No',
    'siblingName1'                => '',
    'siblingDOB1'                 => '',
    'siblingSchool1'              => '',
    'siblingSchoolJoiningDate1'   => '',
    'siblingName2'                => '',
    'siblingDOB2'                 => '',
    'siblingSchool2'              => '',
    'siblingSchoolJoiningDate2'   => '',
    'siblingName3'                => '',
    'siblingDOB3'                 => '',
    'siblingSchool3'              => '',
    'siblingSchoolJoiningDate3'   => '',
    'scholarshipInterest'         => '',
    'scholarshipRequired'         => '',
    'payment'                     => '',
    'companyName'                 => '',
    'companyContact'              => '',
    'companyAddress'              => '',
    'companyEmail'                => '',
    'companyCCFamily'             => '',
    'companyPhone'                => '',
    'howDidYouHear'               => '',
    'howDidYouHearMore'           => '',
);

$I->submitForm('#content form', $formValues, 'Submit');

$I->see('Your application was successfully submitted', '.success');
